### ISSUE TITLE
track duration on upload

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#102]
Upload tracks via mms (should be supported now), and set duration using the `X-Media-Duration` header that should be returned in the response.

**Comment by mbrakken** [comment]
I need to verify upload via MMS behavior, but this is working on the new submissions interface when wav is uploaded directly.

NB: I'll need to test in production, since I don't have an MMS service running locally.

**Comment by jjg** [comment]
I'm working on improving some of these aspects of MMS as we speak; let me know what you want supported and I can confirm/deny @mbrakken  :)

**Comment by mbrakken** [comment]
Thanks @jjg. I haven't tested this yet, but is it safe to assume that when
I upload via MMS, I'll still get back the response from JSFS (eg. the
access_key)?

If so, I think what I have in mind will work, since I'm following up each
upload with a HEAD request for the duration header.

I hope to be able to test out what currently exists this afternoon at some
point, although let me know if I *shouldn't* for some reason.

On Mon, Oct 12, 2015 at 12:56 PM, Jason Gullickson <notifications@github.com

**Comment by jjg** [comment]
Right now that's not necissarilly the case @mbrakken.  What destination format are you planning to store on JSFS?

**Comment by mbrakken** [comment]
wav. NB: conversation on this thread moved into irc

**Comment by mbrakken** [comment]
I have this working in my transocding upload work. Closing.
