### ISSUE TITLE
Downloading indicator hidden behind mobile menu

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#104]
![e4edownlo](https://cloud.githubusercontent.com/assets/7355887/8970735/805a0c26-3608-11e5-967e-98c0757f6822.png)

(Alex, Android phone, Lollipop, Chrome 43, 1:58pm MT, 29 July 2015)

**Comment by prestonaustin** [comment]
@nagapampa In your opinion, would it make sense for us to consider attaching the indicator to the bottom of the tracks object (for all views not just mobile)?

**Comment by nagapampa** [comment]
@preston We have so many things absolutely positioned at the bottom of the screen right now - the mobile menu, More menu, download indicator, player...  They are all fighting for that last spot.

I like your suggestion.  If they are clicking (pressing) from the track level, they should be able to view the indicator at that level too.

**Comment by prestonaustin** [comment]
@nagapampa That was my thought as well, please take a swing at it and we'll
restyle after if need be.

**Comment by preston** [comment]
@nagapampa I think you have the wrong Preston. :)
