### ISSUE TITLE
images downloading / displaying slowly

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#109]
Since yesterday have been noticing distinct lag in album art appearing on homepage and https://wax.capitalcityrecords.ca/albums. 

lbum art for Rend always takes twice as long as everything else. The longest I've counted is 20 seconds before all the art starts to appear. From a UX perspective that is enough time for users to get confused or impatient. 

These are the times when I was able to count and record details (but it has happened more frequently):

- Alex, Windows 7, Firefox 39, 29 July, 2:40pm MT, albums page, 10 seconds; 
  - 30 July, ~9:10am MT, homepage, 10-20s

- tester, Windows 7, Firefox 39, 30 July, 1:45pm MT, homepage, top of the page loaded right away, bottom of the page took 5-10s

Poster art also taking a very long time to load and slowing down browser response time to things like scrolling. Screenshot below is of poster page after it had been open for three minutes. 

![poster page_30072015](https://cloud.githubusercontent.com/assets/7355887/8996737/99c82d94-36d7-11e5-8b1e-628cb87b7cef.png)

Alex, Windows 7, Firefox 38, 30 July, 4:23pm MT,

**Comment by mbrakken** [comment]
The syntax for image processing calls changed, and the app hadn't been
updated yet. That should all be taken care of at this time, but we can
still look at enhancements around:

- [ ] lazyloading images in lists (especially posters, where there are many)
- [ ] maybe adjusting parameters on jpg compression. even with processing,
I agree that the Rend cover still takes an awfully long time.

**Comment by prestonaustin** [comment]
@nagapampa let's merge and deploy @mbrakken's work here, and be sure all our optimizations for client requesting appropriate width and format, and for MMS-caching, are in effect then close with a note for @acecarruthers to retest. I'm not confident there isn't something we don't know about here, but let's look at it again with all our improvements deployed.

**Comment by mbrakken** [comment]
I actually merged and deployed my updates yesterday.

If this stays open, it'll be to keep my points in my prior comment in focus. Otherwise, it can be closed @prestonaustin and @nagapampa.

**Comment by prestonaustin** [comment]
@acecarruthers Please retest performance here and let me know how it feels.
