### ISSUE TITLE
musicat.ca CNAME for mapping root capitalcityrecords.ca domain to app server

### ISSUE THREAD

**Issue by prestonaustin** [therabble/ccr-app#114]
Can we map naked "capitalcityrecords.ca" via a CNAME to "capitalcityrecords.ca.musicat.co" which is itself a CNAME to hostname.of.service.node (or an A record to its IP address)?

I find myself unsure I can do that with the root domain.

**Comment by prestonaustin** [comment]
@acecarruthers Can you ask your DNS contact to set up the following mappings the day we go live:

Add: www.capitalcityrecords.ca. CNAME	www.capitalcityrecords.ca.musicat.co.
Setup and apex record forwarding capitalcityrecords.ca. to capitalcityrecords.ca.musicat.co.

Note that second one can't be a regular CNAME, though it functions the same way in practical sense. Depending on how you handle DNS on ns1 and ns2.epl.ca, they may not have an RFC compliant way to redirect the root/apex record with a CNAME. That's a value added service that most all commercial DNS providers offer, but it's kind of a tricksy thing they do. Strictly speaking you can only have a regular CNAME on the root or apex record for a domain only if you have no other records. Many universities and other entities that do their own DNS and have lots of IP addresses, simply don't do these tricksy things.

So, if this won't work, you may just want to move DNS nameservice to a host that supports this. You don't have to switch registrars to do that, just the nameserver. The alternatives get a bit awkward if we can't do this, and can't move DNS, so let's check this as soon as you get back.

**Comment by jjg** [comment]
I added www.capitalcityrecords.ca and capitalcityrecords.ca to the config of the client Heroku app.  Should be set to respond to those names as soon as the DNS changes go through.

**Comment by jjg** [comment]
Complete @prestonaustin ?

**Comment by prestonaustin** [comment]
This is closed by deprecation yes.

For the record: the site now uses A records to Murfie platform IP
addresses, rather than CNAMEs, so we can support apex name-marketing
compatibly with legacy/RFC-compliant DNS. Without value-added DNS
cleverness this config is unsuitable for CNAME based mapping of requests to
hosted application code such as Heroku offers. So, we moved the app server
to stable IP addressable hosting.

N.B. Moving the service or redirecting around a host outage will therefore
require updates on EPL.CA nameservers as well as to MUSICat.co names.
