### ISSUE TITLE
Security Error on Android Phones

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#117]
users trying to access Capital City Records via an Android mobile device are receiving an error message. Was notified of this by two different users at 10:09 MT and then received the error on my own phone:

![screenshot_2015-08-05-10-13-53-1](https://cloud.githubusercontent.com/assets/7355887/9091031/1add23bc-3b5b-11e5-8b61-89bef8f6d55e.png)

Using Chrome

**Comment by acecarruthers** [comment]
Blackberry users also receiving error messages: 
"Site identity not verifiable. This site may not be trustworthy. Personal information entered on this site may not be protected. The certificate to identify capitalcityrecords.ca has not been verified by a trusted source."

**Comment by prestonaustin** [comment]
@jjg - thoughts?

**Comment by jjg** [comment]
@prestonaustin I was just going to ask you.  I don't have an Android device handy, can you get any extended information about the error?

**Comment by jjg** [comment]
Also does it make a difference what URL is specified (i.e.: http://www.capitalcityrecords.ca vs. http://capitalcityrecords.ca, etc.)?

**Comment by acecarruthers** [comment]
Not on my phone. I get the same error from http://www.capitalcityrecords.ca, http://capitalcityrecords.ca, and https://capitalcityrecords.ca

**Comment by prestonaustin** [comment]
@jjg The problem seems to bother Chrome but not Firefox on Android.

In addition to the NET:ERR_CERT_AUTHORITY_INVALID seen in Alex's report, I
get the following by entering into the advanced and details screens Chrome
offers, see images:

https://goo.gl/photos/RBrpZYjTSzZrogGg9

Anything in there seem not a correct match to the PEM?

N.B. I don't know if this was it was not an issue before the force SSL fix
this AM.

**Comment by mbrakken** [comment]
FYI, Android on my mac has a happy cert:
![screen shot 2015-08-05 at 11 48 29 am](https://cloud.githubusercontent.com/assets/1530955/9091861/39922ac0-3b68-11e5-99ea-337188e569bd.png)

**Comment by mbrakken** [comment]
cert info (chrome, mac):
![screen shot 2015-08-05 at 11 52 31 am](https://cloud.githubusercontent.com/assets/1530955/9091912/8e70d58c-3b68-11e5-9a5f-27af3e0705f3.png)

**Comment by jjg** [comment]
Weird, I don't get any errors on Chromium on Linux either.

**Comment by mbrakken** [comment]
Public key and signature (truncated in the prior screencaps):
![screen shot 2015-08-05 at 12 01 52 pm](https://cloud.githubusercontent.com/assets/1530955/9092157/f1b3952a-3b69-11e5-9477-1ef6f843ab14.png)

![screen shot 2015-08-05 at 12 02 06 pm](https://cloud.githubusercontent.com/assets/1530955/9092160/f509f4da-3b69-11e5-976b-ead524b951c2.png)

**Comment by jjg** [comment]
Looks like we need to include the intermediate certificate in the PEM file we're using on the load balancer.

This will need to be downloaded from the certificate authority's website (in this case, Digicert) and then securely transferred to me so I can install it on the LB.

This page on Digicert's site describes the process.  What we specifically need is the file **DigiCertCa.crt** described in step 2:

https://www.digicert.com/ssl-support/pem-ssl-creation.htm

Once I have that I'll regenerate the PEM, install it on the loadbalancer and we should be in good shape.

@acecarruthers please contact Michael or Lachlan to log into the Digicert site and acquire this file, then send it my way, thanks!

**Comment by acecarruthers** [comment]
I just emailed them now. Will get back to you ASAP

**Comment by jjg** [comment]
New PEM installed, passes my tests & @prestonaustin has confirmed Android & Blackberry is fixed.

Closing but please re-open if additional SSL issues are reported.
