### ISSUE TITLE
"Missing tracking code" message on Google Analytics

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#118]
Received the following notification today when I logged in to Google Analytics:

"No valid tracking code found for property Capital City Records's default URL http://www.capitalcityrecords.ca. Make sure your pages are tagged with a supported version of the tracking code."

**Comment by acecarruthers** [comment]
Any idea why we are receiving this error or how we can fix it?

**Comment by nagapampa** [comment]
@acecarruthers I am logged into GA right now and I am able to see the stats.  Can you take a screenshot of the error message so I know where to look?

**Comment by acecarruthers** [comment]
![ga error message](https://cloud.githubusercontent.com/assets/7355887/9099721/723fc5b2-3b90-11e5-9795-22439fab4c9f.png)

**Comment by acecarruthers** [comment]
I'm not sure what the message "Last detected Aug 1, 2015" is referring to - last time the code was detected? last time the error was detected?

**Comment by nagapampa** [comment]
@acecarruthers I do not see that when I log in... maybe click on ADJUST PROPERTY SETTINGS and change the http: to https:

I am not able to update these settings when I log in.

**Comment by acecarruthers** [comment]
I tried that but there doesn't seem to be a change. I'll give you more admin powers @nagapampa

**Comment by nagapampa** [comment]
@acecarruthers I am on the site and I see the tags being sent to GA, so that's good.  I do see the message now - thank you for the access.

I sent a verification request that may take 24 hours to confirm.

**Comment by acecarruthers** [comment]
Thanks @nagapampa!

**Comment by acecarruthers** [comment]
Received notification from GA that this issue has been resolved.
