### ISSUE TITLE
replace artist banner image

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#119]
Artist Josh Williams has requested we change his banner image to the one below. https://capitalcityrecords.ca/artists/josh-williams 

![widescape](https://cloud.githubusercontent.com/assets/7355887/9097634/e4073be4-3b81-11e5-813b-42e6f810a3c7.jpg)

Thanks!

**Comment by prestonaustin** [comment]
Nice picture :)

@nagapampa can you do this today or ask Marc if he can (so we get it quick
since its an artist request right after launch?)
