### ISSUE TITLE
edit text on FAQ page

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#120]
Under "How can I download music?" replace second paragraph with:

"Log in with your library card and PIN by clicking the Login button in the top right corner. Then click the download button next to the play button on the track you want. Choose the format you want to download. Enjoy!" 

Under "Who is on the jury?" replace Chad Brunet's title with "Program Director, CJSR"

**Comment by nagapampa** [comment]
Will be in next deploy
