### ISSUE TITLE
Google Analytics not tracking all streams

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#121]
I used the Real-Time Event tracker in GA today around 3:30 to check how the site was tracking streams. We noticed that the average session duration on the site was only 3:29 and that didn't seem quite long enough. 

I played Lyra Brown's "Perfect Avocado" and it was registered as a streaming event. When the next song, "The Language of Eyes," came on automatically, the site did not register a new streaming event. 

@nagapampa can you think of a way to make a stream that starts automatically register as a new event in GA? I've been Googling around and haven't found an explanation yet. Thanks!

**Comment by mbrakken** [comment]
I see the ga call is in the action handler. I'd move it into the player
service, right where I have the call to the logger service.

**Comment by nagapampa** [comment]
@mbrakken are you talking around line 66 before the logger.logPlay(track); ?  is the playSound method called when the next track plays?  Thanks Marc.

**Comment by prestonaustin** [comment]
@nagapampa that should work fine as context, even if that's not what Marc
meant.

**Comment by nagapampa** [comment]
@prestonaustin I moved the call to the player service and took it out of the handler.  I tested and saw a new GA call being sent on track changes.  

@acecarruthers This will be in the next deploy.
