### ISSUE TITLE
Test Report for SOCAN by Aug 19

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#122]
This must include a Monthly Sales Reporting File (incl. Header Record Layout and a Detail Record Layout) and a Unique Visitors Report File (incl. Header Record Layout and a Detail Record Layout). 

CSI/SOCAN Joint Reporting Format: https://drive.google.com/open?id=0B56HcVGi1B3nVlp6dFZmOGNGeVE 

Customer ID: EP-188326
Service Name: CapitalCityRecords
Tax Province: AB
Deal Type Code: STREAM

If you can email me the reports I'll email them on to SOCAN to review. Once we've got the data reporting structure confirmed, they'll explain to us how to automate the process, so we can send monthly reports. 

Note: CSI is still figuring out how they are going to charge us because our project is unique. Once they receive the data requested in #47 they will tell us what deal type code they want us to use and we'll need to send them a test report as well. It will most likely be almost identical to the one for SOCAN.

**Comment by acecarruthers** [comment]
@prestonaustin @lahollen do you think this will be available tomorrow?

**Comment by prestonaustin** [comment]
@acecarruthers we are badly behind this week due to focus on audio platform
bug, and an unrelated hardware crash that we recovered from without
incident (CCR is not impacted) but had to focus on restoring redundancy
(done), then fixing the root cause (in progress). I'll look at this report
issue with @nagapampa in the AM and try to get you a report within
Wednesday. One of us will provide an update by mid-day tomorrow.

**Comment by acecarruthers** [comment]
@prestonaustin Sorry to hear about the hardware crash! Thanks for the update.

**Comment by acecarruthers** [comment]
Revised date for this is the morning of Thursday Aug 27

Please send me via email a .txt file the conforms to the specifications in the CSI/SOCAN Joint Reporting Format: https://drive.google.com/open?id=0B56HcVGi1B3nVlp6dFZmOGNGeVE 

See pages 1-2 and 7 for file naming conventions.

See first comment for other relevant details.    

Note: for SOCAN, we only need to report on STREAMS. We will need to send CSI a report on downloads that follows all of the same rules, but only after they have figured out how to charge us.

**Comment by nagapampa** [comment]
![socan](https://cloud.githubusercontent.com/assets/2964839/9531270/b85d15fe-4cca-11e5-865e-930fda809aca.png)

@acecarruthers For now, the start and end date (as well as filename) are hard coded.  I will email you the generated TXT file or you can log in and run it yourself.
