### ISSUE TITLE
Music not playing on Capital City Records

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#125]
As of 2:20pm MT this afternoon I haven't been able to stream any music on Capital City Records on any browser or device. Sometimes album art is broken also on the album page and on the playbar. 

See screenshot from 3:13pm MT Chrome desktop https://capitalcityrecords.ca/albums/choir-and-marching-band-life-found-on-superhot-body-only-one-light-year-away 

![streamimageerr](https://cloud.githubusercontent.com/assets/7355887/9369240/23e609b2-4685-11e5-855a-89fc3acff639.png)

**Comment by jjg** [comment]
Investigating

**Comment by jjg** [comment]
@acecarruthers I believe this is resolved but please re-test (you may have to clear your cache) and leave a comment if there are ongoing issues.

**Comment by acecarruthers** [comment]
@jjg everything is working fine again! That was fast! What was the problem?

**Comment by jjg** [comment]
I need to review with @mbrakken but something in the code is relying on a default routing mechanism on our loadbalancer that I have slated to be depreciated.  It was disabled while we were upgrading the storage system that gave us trouble yesterday.  Once I saw this issue I re-enabled the routing.
