### ISSUE TITLE
Music not streaming

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#126]
Received notification from a user that they cannot stream tracks on Capital City Records. I cannot either. Images are resolving quite slowly and sometimes are breaking - specifically album covers on album pages. See screenshot below

User, Windows 7, Chrome & IE, ~4pm, https://capitalcityrecords.ca/albums/columbus-commonwealth and https://capitalcityrecords.ca/albums/the-duettes-your-little-voice 24 Aug 2015

User 2, Mac desktop, Chrome & Safari, ~4pm various albums 24 Aug 2015

Alex, Windows 7, Firefox & Chrome, 4:10pm MT, https://capitalcityrecords.ca/albums/f-and-m-at-sunset-we-sing, https://capitalcityrecords.ca/albums/josh-williams-time-and-faith 24 Aug 2015

![2015-08-24 16_08_30-at sunset we sing f m _ capital city records](https://cloud.githubusercontent.com/assets/7355887/9453925/52414f98-4a7b-11e5-8bc3-979cadc5c366.png)

**Comment by prestonaustin** [comment]
Looking into it with @jjg and @mbrakken, will update.

**Comment by prestonaustin** [comment]
@acecarruthers should be back now, my tests that failed now pass, will
follow up with more info later after we analyze the failure, but please
retest. Mention @jjg if you see errors.

**Comment by acecarruthers** [comment]
Thanks @prestonaustin it is working for me too

**Comment by prestonaustin** [comment]
@acecarruthers Thanks for the notice. This was a pretty obscure
problem. Hourly extra backups we setup last week after prior data loss,
just to be conservative and have instant recovery locally available, ran a
root filesystem out of space, crashing the service and its ability to
notify us. @jjg has cleared the extra backups out and backed the schedule
down to once a day. (An once of caution 24 times a day was a few too many
pounds of cure between regular health checkups) Jason and Marc are
reviewing multiple platform concerns tomorrow anyway, and I'm adding
normalizing the admin routines for the CCR environment, and an external
streaming health monitoring provision to the agenda.
Cc: @mbrakken
