### ISSUE TITLE
Submissions Process bugs and improvements

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#128]
List of bugs noticed in the first call for submissions that need to be fixed/tested as well as improvements to the tool that occurred to us the first time around.

Artist Submissions http://submissions.capitalcityrecords.ca/submit/
- [x] not all audio files uploaded successfully so jury wasn't able to listen to all tracks (I believe this is fixed, but we need to test)
- [x] Collect track duration data

Jury Tool http://submissions.capitalcityrecords.ca/submissions
- [ ] Jury comments, recommendations, rejections wouldn't save/disappeared when you refreshed the page
- [ ] Include genre and other collected data in submission record for jury to see
 
Full Album Submissions http://submissions.capitalcityrecords.ca/complete-submission?auth=51d214387aeb849f0eca83d93c8232b473615352
- [ ] We encountered a problem last time (artist couldn't upload her banner image) because the tool didn't support submissions for multiple albums from a single artist. It is likely that we will receive new submissions from artists who submitted last time, so we will want to test that it works all the way through. 
- [ ] Recommended maximum size or recommended dimensions for images/ability to select image thumbnails in submission form.

Invitation Tool http://submissions.capitalcityrecords.ca/invite
- [ ] Send localmusic@epl.ca copies of sent invitations so we have a record of the unique links sent to each artist
- [ ] "Reject" button sends Deferral email

**Comment by acecarruthers** [comment]
Text for the Deferral (Reject) email is on page 2 of this document: https://drive.google.com/open?id=17hdD3rlN3ZZkYGq2TEqqgspcXQcB995KF6tNTUYrAKc

**Comment by acecarruthers** [comment]
@prestonaustin I think you mentioned a few other updates to the submission process in our meeting last week - could you add them to Github and then connect them with this issue? Since I'll be away next week, I'll be giving Peter an intro to Github so he can stay on track of how the Call for Submission fixes are going and respond to questions as necessary.

**Comment by mbrakken** [comment]
- [ ] persistent under consideration queue during jury process
- [ ] cc epl on initial invitation emails (maybe other messages, too)
- [ ] sort fall 2015 & prior round in publish interfaces (easily id what's
new for review)
- [ ] standardise how artists declare they don't have a label

**Comment by acecarruthers** [comment]
Thanks @mbrakken - I think that your second point is covered under invitation tool in my first post, but this seems like a good list to me. 

@pschoenberg will be the contact if you have any questions about this work next week.

**Comment by mbrakken** [comment]
I'm prepared to deploy a new submission interface for testing. I have a few outstanding questions before considering it complete, though:

Should we send emails upon initial submission? If so, what should be their copy to the appropriate recipients (submitter & EPL, I assume)? NB: we did not send out emails at this point in the last round.

I have a new design concept in mind for the next jury interface, in part to contend with the desire to show all information included in submissions as well as other features (eg. the 'under consideration' queue). I'll put together a mockup before I get too far into it.

**Comment by prestonaustin** [comment]
At this time, @mbrakken, let's not add that email on submission. Break it
out into a separate issue for work to consider, under appropriate
unscheduled potential work milestone and tags. I now think it will cause
ongoing work for EPL, and may lead to a lot of child issues we won't be
able to address in a timely manner.

**Comment by pschoenberg** [comment]
I agree with keeping the email as a separate issue.

Slightly concerned about a new jury interface - that sounds like much more work than fixing the small-ish issues with the current one.   If that is the best way to get to where we need to be in two weeks, then no problem.

**Comment by mbrakken** [comment]
I just deployed the submission interface: https://capitalcityrecords.ca/submit

I need to test upload behavior in production with respect to converting files into wav during upload, but beyond that, feel free to take a look and provide feedback @acecarruthers and @pschoenberg.

**Comment by pschoenberg** [comment]
Looks good visually.  Typo of ULR for Youtube instead of URL.

Have to grab a couple of music files to complete the upload test.

**Comment by pschoenberg** [comment]
Tried to upload an MP3 grabbed from our Freegal site.   Miles Davis So What.

Got an error message.  

![image](https://cloud.githubusercontent.com/assets/15022644/10498669/1a0b5066-7289-11e5-9913-c7a3e7c41d3a.png)

**Comment by mbrakken** [comment]
Uploads don't work at the moment. I was testing a different approach to how
the data is actually sent to the server, and need to revert back to the
prior tested approach for now.

I'll let you know when that's updated. The approach I'm hoping for but am
temporarily moving away from should alleviate any playback challenges out
of the gate.

**Comment by mbrakken** [comment]
Yup. I hadn't switched back from some tests at that point. The version up
right now successfully runs through end to end. Data for stuff I just
uploaded can be found here:

https://ccrapi3.murfie.com/submit/albums/fall-2015/marc-and-stuff-marc-s-tests

I'll still want to get the stuff I was testing today working, but some
other things need to be squared away for that all to work.

**Comment by acecarruthers** [comment]
This is looking great @mbrakken! I like the fields and upload tool all on one page and I like that "independent" is automatically suggested as a record label. I tested it through this afternoon (Oct 22) in Firefox 41.0 and Chrome 46.0. on my Windows 7 Desktop. Here is some feedback

- [ ] No need to include artist social media fields incl. YouTube, social media, website at this stage
- [ ] Header edit - replace Capitol with Capital 
- [ ] Playback worked when I uploaded a WAV, MP3, ogg, aiff files, but not FLAC, AAC, ALAC – in Firefox & Chrome
- [ ] On confirmation page, link to FAQ should direct to https://capitalcityrecords.ca/faq 
- [ ] In Firefox, Album genre defaults to World Music, change to select a genre
- [ ] Green confirmation box in bottom corner of the screen – please make EPL green (#7bc143)

Before we go live, I'll want to test the process from beginning to end. Here are some notes on that: 
- [ ] Original call for submissions process had an intro page with a summary of the legal context and the amount of the honorariums. Submitters had to acknowledge these details before they uploaded content. When we go live, that page should precede this one. 
- [ ] How can I track submissions as they come in? If submissions automatically appeared in the jury tool that would be almost enough. Then I can test that the music plays and get back to the artist if there is a problem. The only thing is that they jury should not have access to the submitter name and contact information. Only I can have access to that. Tied to #151

**Comment by mbrakken** [comment]
@acecarruthers A quick update: I have a series of changes I can roll out (the checked-off stuff). The only thing currently blocking me relates to transcoding media during upload (to store as wav). I have it working locally, but it required some changes to the transcoding system because there are some assumptions the transcoder makes that don't work with the version of the file storage system currently in place for ccr. 

I've proposed some changes to @jjg and he's proposed some alternatives. I'll negotiate with him on a solution.

Meanwhile, I'll pick up @nagapampa's jury interface work to get a version together where you can at least review submissions as they come in.

**Comment by mbrakken** [comment]
I talked with @jjg about ways to handle MMS' expectations re: transcode on upload. I didn't get around to testing it yet today, but I have full confidence it'll work since I had forgotten that a version of it is what we are currently doing for Murfie's new download processing system. I believe I'll be able to get it out the door tomorrow.

**Comment by mbrakken** [comment]
I've tested AAC in my latest work (well, an itunes download, which I assume is aac), and am currently downloading some lossless files to test as well. Signs look goodl.

**Comment by mbrakken** [comment]
I've verified FLAC in production. ALAC transcode currently fails on MMW. I've submitted an issue there. 

Is this actually a problem? Will removing ALAC as an option actually interfere with anything?

**Comment by kellyhiser** [comment]
I don't think removing ALAC as an option should be a problem - I seem to remember we had no or very few ALAC submissions last time around. @acecarruthers can you confirm?

**Comment by prestonaustin** [comment]
FWIW - I considered excluding it at the outset as it is a pretty low value
format on the music production side, serving well only in "exclusively
Apple gear" environments. We should ideally ask for FLAC as preferred, then
WAV/WAVE, then MP3, then anything else.

**Comment by mbrakken** [comment]
I agree, and will remove ALAC as an option. I think exactly 0% of artists will be affected by this. Note that it only relates to uploads. ALAC will remain a download option.

**Comment by mbrakken** [comment]
This issue is currently over-specified. I'm splitting it into separate issues for each interface for better state management. I'll close this one when that's done, but reference it in each related issue.

**Comment by mbrakken** [comment]
Moving this issue into issues #151, #161, #162, #163, #164.

Closing here.

**Comment by acecarruthers** [comment]
@kellyhiser @mbrakken no artists used ALAC last time. It is 100% cool to drop it.
