### ISSUE TITLE
CSI requests more data

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#134]
CSI has requested more data from us in order to move forward. Can you please send me the following numbers: 
- Total tracks downloaded (Aug 5 - present)
- Total tracks streamed (Aug 5 - present)
- Total tracks downloaded (Aug 28 - present)
- Total tracks streamed (Aug 28 - present)
- No. logged in users who have streamed (Aug 28 - present)
- No. logged in users who have downloaded (Aug 28 - present)
- Total No. logged in users who have streamed/downloaded (Aug 28 - present)

This does not have to be formatted in any particular way and I do not expect to have to send it again, so don't worry about setting up a button that provides this data. Just an email would be fine or even reporting the data in a comment in this issue thread.

**Comment by acecarruthers** [comment]
I'm thinking maybe @lahollen or @nagapampa can help me with this?

**Comment by nagapampa** [comment]
@acecarruthers You should be able to get these numbers from the current report and from GA.  That user's report I just sent has the total tracks streamed (if you add up all the numbers in the records) - same with number of users who streamed.  I think all the download information is in GA.  

I'm not sure able the number of users who have downloaded.  We are tracking the streams in the app, and GA is tracking downloads, but not on a per user basis.

**Comment by acecarruthers** [comment]
Hi @nagapampa - you're right, I didn't ask you to track downloads per user because the first time I talked to CSI they said we wouldn't need to. Sorry about that.  I pulled together the data I could find and found some confusing discrepancies in the total number of tracks streamed. 

1. The SOCAN sales report - between July 9 and Aug 27 - total streams: _153_ (this is counting all of the total units in field # 23)
2. The SOCAN UVR report - between July 9 and Sept 15 - total streams: *1033*
3. Google Analytics -between Aug 5 and Sept 15 - total streams: *7331*

For the discrepancy between 1 and 2: it is possible that the were 880 streams between Aug 28 and Sep 15, but I think it is unlikely. Looking now at the SOCAN sales reports I am noticing a couple different details that seem like this report didn't end up looking like it was is supposed to. I will go over those details in a different issue thread tomorrow. 
 
For the discrepancy between 2 and 3: One guess I have is that Google Analytics tracks every time someone clicks on a song - and records it even if they immediately turn it off. I remember agreeing that the server should only track how many people get past 6 seconds. Can you confirm that this is the case? Or propose an alternative explanation? 

The Google Analytics data is the only data I have that begins on Aug 5th, the launch date of the site. We started tracking on July 9 because that was the launch of the beta test and we wanted to make sure that artists were paid for music listened to during the test. What CSI is interested in right now is not data on which artists to pay, but data that reflects the regular usage of the site. If the UVR data represents the correct number of total streams, is it possible to query the server log to find the total number of streams between Aug 5 and the present? 

Thanks

**Comment by nagapampa** [comment]
[EP-188326_STREAM_20150930_20150918_211015.txt](https://github.com/therabble/ccr-app/files/2152/EP-188326_STREAM_20150930_20150918_211015.txt)
[EP-188326_STREAM_20150930_20150918_211015_UVR (2).txt](https://github.com/therabble/ccr-app/files/2153/EP-188326_STREAM_20150930_20150918_211015_UVR.2.txt)

**Comment by nagapampa** [comment]
Those are the files for 8/5 - present

**Comment by acecarruthers** [comment]
Thanks @nagapampa - There is a big difference in the data (and I like these numbers way better!!)

Here's the total number of streams I pulled from these two files:
Sales: 9731
UVR: 9687
I'm not sure which one is correct. Can you explain why these are different and why these numbers are so different from the earlier numbers? It might be easier to discuss this over Hangouts. Maybe this afternoon if that works well for you.

**Comment by nagapampa** [comment]
[EP-188326_STREAM_20150930_20150918_211015.txt](https://github.com/therabble/ccr-app/files/2178/EP-188326_STREAM_20150930_20150918_211015.txt)
[EP-188326_STREAM_20150930_20150918_211015_UVR.txt](https://github.com/therabble/ccr-app/files/2177/EP-188326_STREAM_20150930_20150918_211015_UVR.txt)


@acecarruthers  I made one small change but still can't get them to match up exactly.  Still looking into it but I wanted to get you a copy of the reports today.  This is for 8/5 present.

**Comment by nagapampa** [comment]
[EP-188326_STREAM_20150930_20150918_211015.txt](https://github.com/therabble/ccr-app/files/2179/EP-188326_STREAM_20150930_20150918_211015.txt)
[EP-188326_STREAM_20150930_20150918_211015_UVR.txt](https://github.com/therabble/ccr-app/files/2180/EP-188326_STREAM_20150930_20150918_211015_UVR.txt)

@acecarruthers  Here are the reports for 7/9 - present

**Comment by nagapampa** [comment]
[EP-188326_STREAM_20150930_20150918_211015.txt](https://github.com/therabble/ccr-app/files/2185/EP-188326_STREAM_20150930_20150918_211015.txt)
[EP-188326_STREAM_20150930_20150918_211015_UVR.txt](https://github.com/therabble/ccr-app/files/2184/EP-188326_STREAM_20150930_20150918_211015_UVR.txt)

Found the issue.  Updated reports here.  From July 9 - present

**Comment by nagapampa** [comment]
[EP-188326_STREAM_20150930_20150918_211015.txt](https://github.com/therabble/ccr-app/files/2186/EP-188326_STREAM_20150930_20150918_211015.txt)
[EP-188326_STREAM_20150930_20150918_211015_UVR.txt](https://github.com/therabble/ccr-app/files/2187/EP-188326_STREAM_20150930_20150918_211015_UVR.txt)


From July 9 - present

**Comment by acecarruthers** [comment]
Thank you, Carie! Awesome! It looks like you sent me the reports from July 9 - present twice - I also need from Aug 5 to present :)

**Comment by nagapampa** [comment]
@acecarruthers Those are from different times.  I just commented incorrectly.

**Comment by acecarruthers** [comment]
Oops! Thanks @nagapampa

**Comment by acecarruthers** [comment]
@nagapampa I was able to collect and send all the new data that CSI requested by combining Google Analytics and the reports you provided. This has raised a question for me, though: are we tracking downloads somewhere other than Google Analytics?

**Comment by nagapampa** [comment]
@acecarruthers Not that I can see in the the project.  The logger is STREAM.

**Comment by prestonaustin** [comment]
Clarify for me - is there no logger at all on the download controls, or are
we logging them as streams? (The latter would be an error, they are
technically identical but distinct for purposes of counting)

**Comment by acecarruthers** [comment]
In either case, @prestonaustin we need to start tracking downloads right away. In order to provide us with a license to download music, CSI requires that we send them a Monthly Sales Report for downloads as well as streams. It will follow the exact format for Monthly Sales Report as the SOCAN report. Hopefully we can pull something together using Google Analytics for the first report.

**Comment by prestonaustin** [comment]
Understood. Originally we specified to do so, so I am trying to figure out
what needs doing.

**Comment by mbrakken** [comment]
Hi @acecarruthers. We are definitely logging downloads as distinct events, and have been probably from the beginning: 

https://log.murfie.com/?app=4e392d7402d16170a352212f74ae2315&event_type=download

It looks like the code that generates the report is only looking at streams, eg:

**Comment by mbrakken** [comment]
@acecarruthers I accidentally saved my prior comment before I was finished, so you probably got emailed the incomplete version. Please see in github for the complete text.

**Comment by acecarruthers** [comment]
Thanks @mbrakken that is great news! The reporting format provided by the organizations we are reporting to requires that we create different reports for downloads and streams. I am still waiting on essential information from one of those organizations on how to report downloads.

**Comment by mbrakken** [comment]
@acecarruthers Is the report format for the organization you have information from somewhere I can find? I'm still getting up to speed on the current state of everything, so my apologies if this is something I should already know about.

**Comment by acecarruthers** [comment]
Here is the reporting format: https://drive.google.com/open?id=0B56HcVGi1B3nVlp6dFZmOGNGeVE 

A summary of the context - who these organizations are and why we need to send them these reports - is here: https://drive.google.com/open?id=1_uskLeYpKjgiw9xTKSjH2ZlKqFUYJGjZ8sz7iGbkweA

**Comment by mbrakken** [comment]
Thanks!
