### ISSUE TITLE
Please put attached image on the homepage carousel

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#135]
Please have the banner link to http://epl.bibliocms.com/launch-event/ 
There is no need for additional text overlay. 

This only needs to be up until Wednesday Oct 7. 

Thanks!
![oboe_ccrheaderlyrabrown_980x450_september2015](https://cloud.githubusercontent.com/assets/7355887/10233156/22094208-684a-11e5-9245-bc28f047c778.png)

**Comment by mbrakken** [comment]
@nagapampa I just assigned this to you. Let me know if that was wrong of me :)

**Comment by acecarruthers** [comment]
@prestonaustin @nagapampa This issue is quite time sensitive (as you can see from the text on the banner). If it isn't possible to put this up today and then remove it on Wednesday, we can mark this issue as closed.

**Comment by nagapampa** [comment]
@acecarruthers This has been deployed.  Please refresh.  It should be the 4th in the slide.  There is a MORE button at the top right that goes to the link you sent above.

**Comment by acecarruthers** [comment]
Thanks @nagapampa!!

**Comment by acecarruthers** [comment]
@nagapampa can you remove the Lyra Brown image from the homepage carousel next chance you get? The event has passed. Thanks!

**Comment by nagapampa** [comment]
@acecarruthers This will be in the next deploy.

**Comment by acecarruthers** [comment]
thanks!!
