### ISSUE TITLE
Jury interface v0.2

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#151]
Relevant parts pulled out of #128 
______
Prior version at http://submissions.capitalcityrecords.ca/submissions

Bugs from prior version:
- [x] Jury comments, recommendations, rejections wouldn't save/disappeared when you refreshed the page
- [x] Include all collected data in submission record for jury to see
- [x] persistent under consideration queue during jury process

Jury interface should be within the admin context. We'll need to make sure that non-admins with access to the jury stage can still access.

Path: https://capitalcityrecords.ca/admin/jury

Proposed UI (rough sketch):
![20151019_141420](https://cloud.githubusercontent.com/assets/1530955/10588541/65be8b0e-766c-11e5-8216-e410a021cea5.jpg)
Essentially, the left sidebar contains the list of all submissions under their current queue. In the sketch, the Pending queue is active. If the "Your queue" queue were active, the pending queue would collapse and "Your queue" would expand and be scrollable.

The main section of the UI has all relevant information for the juror, including bio , links to artist info, etc. Currently I have this all in a single stack. We may consider alternatives, but I want simplicity for now.

On the right are the list of actions: Recommend, Flag, Add note, Add to queue, Skip.

Add to queue is new; it should allow a juror to create a unique-to-themselves persistent list of things they're considering. Skip should also be persisted, and be unique to the Juror using the interface. 

Essentially, the interface will show information about *one* submission at a time, with jurors able to jump to arbitrary points via the lists on the left.

Development of UI and backend processes can happen separately. The interface will create `juror-review` objects, which will relate to the juror and the submission. A juror can only create one review for a submission. Types of reviews relate directly to the queues, eg `recommendation`, `flag`, `note`, `skip`, `personal-queue`.  A new review of an already-reviewed submission essentially means an update of their prior review, not a new review

**Comment by mbrakken** [comment]
The interface should present to the jury all information submitted by the artist.

On the last version, there were concurrency issues related to saving of jury reviews. These should all be resolved given the current API, but we will need to verify that concurrent operations do not result in data loss or mis-placement.

**Comment by acecarruthers** [comment]
Thansk @mbrakken, I think the jurists will really appreciate the "Your Queue" option. Feedback: 

1. Maybe this is already in your plan, but when a jurist clicks Recommend, Flag, Skip or Add to Queue, I think the next submission in the line should appear in its place. (When they Add a Note, it should stay on the same submission)

2. What information is shown in the side lists? I’d like to see both the artist name, the full album name and the genre if possible. 

3. There will need to be space on each individual submission where you can see the notes others have put on it. 

4. as per #128, the jury interface should not show social media info (bc I don't think we should collect it at this stage) and it shouldn't show the submitter's name or email address for privacy reasons. I will need to have access to that data myself, though, somewhere.

**Comment by mbrakken** [comment]
@acecarruthers:

1. Yup. That's the idea.
2. I was thinking artist name / album title, but it should be easy to add in genre, too.
3. Yup.
4. Sounds good. Submitter info is definitely not intended for the jurors. Pulling out social media stuff (here and the form) is trivial.

For inviting jurors, I'm assuming you already have your intended list. I'm working to get together a process for formally inviting them / getting them urls to access the form, log-in info, etc. Do you have copy for an email that will include that info?

I also hope to have together a system where you can easily change email copy without dev work, but I don't know if I'll have that together in time.

**Comment by acecarruthers** [comment]
@mbrakken The jurors will be the same as last time. Will their existing profiles work?

**Comment by acecarruthers** [comment]
if not, here are the details that I think you'll need. https://drive.google.com/open?id=1XUAMAFfnCrt7AGGkhQ77aqlcCV9L65BTTzP6ZF_LDuw

**Comment by mbrakken** [comment]
- [ ] jury interface should auto load to the first submission in the queue (sorted by submission date?)
- [ ] admins should see submitter info

@acecarruthers a first version of the jury interface is alive: https://capitalcityrecords.ca/admin/jury
Buttons on the right don't do anything yet, and I stripped out any expand / collapse of the categories to the left for the moment, but tracks are previewable.

**Comment by acecarruthers** [comment]
Hi @mbrakken , I am unable to access the jury interface because I am unable to authenticate. It appears to be the same problem as #157

**Comment by mbrakken** [comment]
@acecarruthers I believe #157 should be resolved currently.

**Comment by mbrakken** [comment]
(as of about 2 minutes ago)

**Comment by acecarruthers** [comment]
Hi @mbrakken, with submissions running until Dec 3, the jury is expecting to have access to the jury tool as of Dec 4. Think I can be running tests on the jury tool/jury authentication by Nov 30 at the latest? If at any point you don't think this timeline will work let me know and I'll give the jury a heads up.

**Comment by mbrakken** [comment]
This seems more than reasonable @acecarruthers. I'm hoping you can end to
end test the middle of next week.

**Comment by acecarruthers** [comment]
@mbrakken oh amazing! Thanks! I will be out of the office between Nov 19 and 23 - back on the 24th.

**Comment by acecarruthers** [comment]
Hi @mbrakken, any updates for me?

**Comment by mbrakken** [comment]
I should have something for you very soon @acecarrthers. I had been
debating different approaches to handle this, and while I was waking up
this morning a rather nice one occurred to me. I'm testing it out locally,
and so far it all seems to be working. I'll deploy and give you a login
once I feel it's there, which should certainly be today.

**Comment by mbrakken** [comment]
@acecarruthers I just sent you an email outside this thread with credentials for a test juror account. Other than the juror's queue, I think every thing is set.

**Comment by mbrakken** [comment]
I believe this is done enough to close. Interactions within the jurists' queue could be improved, but I feel like it's all workable as is. I'm going to close this, but feel free to reopen if I'm wrong @acecarruthers.

**Comment by acecarruthers** [comment]
Agreed that the jurists queue interactions are just fine. After reviewing functionality on Chrome and Firefox this morning and this afternoon, there are some bugs I noticed and small fixes I'd like to suggest for this tool. 
- [ ] In both Chrome and Firefox when I had flagged a submission and then unflagged it and tried to recommend it, the recommend function did not work. The opposite was also true. When I had something recommended and then removed it from recommended and tried to switch it to flagged, the flag function didn't work. When I clicked either the flag button or the recommend button, respectively, there would be no response. 

In the last round there were some use cases where this would have been an issue: Jurists picked an album only to discover that the artist had moved away and shouldn't be considered or that the artist's first album had already been picked, so their second album was out of the running - They would have had to move the submission from recommend to flag.  
- [ ] Dialog boxes in Firefox and Chrome give the user the option of selecting "Prevent this page from creating additional dialogs". When I selected "Prevent this page..." in Chrome I couldn't Recommend or Flag or add notes at all anymore. The buttons no longer responded to being clicked. When I selected this in Firefox, I could still recommend or flag or add a note but no dialog boxes appeared to give me the option to add content. The note just says "note by Marc Test". Is there a way to remove this option from the dialog boxes? I can imagine a jury member clicking this by accident or before they realize how essential dialog boxes are to the tool and then getting frustrated. 
- [ ] Small typo in the note and flag dialogs: should be "required"
- [ ] This is just nitpicky, but the dialog box in Chrome says "The page at https://capitalcityrecords.ca says: "  - can that be removed? It is unnecessary text.

**Comment by mbrakken** [comment]
Ahh. Right. That first one fell off my radar (for some reason the id for
the review hangs around in local memory after it's deleted, which
interferes with a new thing being created with that id. A hard refresh
alleviates the problem, but that shouldn't be necessary).

For everything else, I'll look at wiring up a custom modal rather than the
current default prompt box. Everything you raise about the browser default
version cannot be worked around.

**Comment by mbrakken** [comment]
@acecarruthers The first point is better addressed by the API. I have an update tested locally that resolves this, I'll deploy it later this evening.

I'll try to knock out the others soon.

**Comment by acecarruthers** [comment]
Hi @mbrakken I tested the first one (flagged>recommend, recommend>flag) and it works great. Thanks! I noticed the other points have check marks beside them but I didn't see any changes to the dialog boxes on the tool. Can you give me a heads up when I should see those? 

I'm putting together an email to send to the jury tomorrow that includes some information about the changes to the jury tool interface. I would like it also to include a little information on how they can log in.Can you confirm that process for me? Will they be able to use the email address and password they used last time? Right now my email says "You can sign in at https://capitalcityrecords.ca/admin-login with the email and password you used earlier this year. If you have trouble remembering your password let me know and I'll arrange a new one for you." Edits appreciated. 

Last thing is that I noticed that some submissions don't have a submitted date and time, instead they say "Submitted no date". I don't think this is a blocking issue at all, I just thought I'd point it out in case it ended up being tied to something else. Examples of "Submitted no date" submissions: Everybody's KINg, K Points, Feels Like Home and maybe 6 others.

**Comment by mbrakken** [comment]
Hi @acecarruthers, the other night I mostly implemented everything to swap
out the browser default popup with a custom one, and just need to clean it
up and make sure I didn't break anything with the modified process flow.
I'd hoped to have that out early yesterday, but sudden Murfie needs ended
up occupying my attention. I should be able to get it all out today at some
point. I'll let you know when it's out.

As the emails, I believe that will be fine, although I'd give them
https://capitalcityrecords.ca/admin/jury as the address to go to. That will
redirect to login and automatically take them back once they've signed in.
I'll use the same password as last time as well (the same as for the test
juror I sent you).

I also just sent you the list of jurist emails that I have in order to
confirm that it is in fact the same list this time out.

**Comment by acecarruthers** [comment]
Thanks @mbrakken. I'll email the jurists today once I hear from you that the popup fix has been pushed out.

**Comment by mbrakken** [comment]
Okeydokey. Version with custom modal input is now out. Accounts for jurists have been created. I think it's all set.

I'll let you close this. Please let me know either way.

Next I'm finishing off the updated invite interface, and then the artist completion stuff.

**Comment by acecarruthers** [comment]
Thanks @mbrakken. Everything is working great. I have contacted the jurists, so we are good to close this!
