### ISSUE TITLE
Artist page formatting error

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#152]
I have just noticed some strange formatting errors on artist pages. An image of Cayley Thomas' page is below with the JS console open as an example. The artist title text is now black instead of white, the YouTube embed is missing, and after I clicked on the twitter logo the word "twitter" appeared above the logo in blue. 

I have noticed this on:
Cayley Thomas https://capitalcityrecords.ca/artists/cayley-thomas Oct 22, 2:30 on Firefox 41.0 and at 2:35 on Chrome 46.0.2490.71
Marco Claveria https://capitalcityrecords.ca/artists/marco-claveria-project 2:32 Firefox 41.0
Nature Of https://capitalcityrecords.ca/artists/nature-of 2:40 Chrome 46.0.2490.71

**Comment by acecarruthers** [comment]
![artist_formatting](https://cloud.githubusercontent.com/assets/7355887/10677770/9c7b29d4-78cb-11e5-9849-6173c5fdeda1.png)

![natureof_err_chrome](https://cloud.githubusercontent.com/assets/7355887/10677795/b9cbb35a-78cb-11e5-867c-fbaf702dd784.png)

**Comment by mbrakken** [comment]
The video doesn't seem to exist any more: https://vimeo.com/84088486
It will need to be replaced or cleared outright.

Other fixes will roll out soon.

**Comment by acecarruthers** [comment]
I went to go remove the video from Cayley's artist page, but I can't seem to access the Artist and Albums page of the Review and Publish interface http://submissions.capitalcityrecords.ca/review-and-publish/submissions. I am able to access the posters page.
