### ISSUE TITLE
Tracks not finishing

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#153]
I was listening to Choir and Marching Band tracks 1 and 2 and they both stopped mid song. I tested both twice. This only happens in Firefox. In Chrome they play all the way through, but then track 1 stopped at the end and didn't move forward to track 2 as I noted in issue #123. Am currently listening to other albums to see if they have the same error.  

https://capitalcityrecords.ca/albums/choir-and-marching-band-life-found-on-superhot-body-only-one-light-year-away Firefox 41.0, Oct 22, ~2:25pm MT, windows 7 desktop

**Comment by kellyhiser** [comment]
@acecarruthers I'm closing as I think this is covered in #123. let me know if there's a reason to keep this open.
