### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#154]
Attempting to login using library card and PIN is having a strange result. The nav bar that typically says "Full Collection My Collection Logout" temporarily flashes on the screen and then disappears - replaced by "Login." This also happens when you are prompted to login when you try and download an album. Here is a screenshot of the browser console from when Peter tried to login on Chrome.
 
![loginerr_console](https://cloud.githubusercontent.com/assets/7355887/10833223/f9c418e6-7e55-11e5-916a-27b983c58c7c.png)
Here is the console from when he tried to login using Firefox:

![loginerr_console_firefox](https://cloud.githubusercontent.com/assets/7355887/10833239/155ef724-7e56-11e5-924f-239609188ce3.png)

This has been tested twice on Chrome, twice on Firefox on 3 separate PCs running Windows 7 between 3 and 4pm MT with the same result.

**Comment by mbrakken** [comment]
This should be resolved now, @acecarruthers. I authed with the test credentials and all went well.
