### ISSUE TITLE
Can't access artist page editor or reports page

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#157]
The link that usually takes me to the artist/album page editor now takes me to a blank page: http://submissions.capitalcityrecords.ca/review-and-publish/submissions/ This may be related to my most recent comment on #152 

The link that took me to the reports interface now prompts me to authenticate. My email address and password are not accepted and I'm redirected to the Capital City Records homepage. https://capitalcityrecords.ca/admin/reports

Tested on Firefox 41 and Chrome 46.0.2490.80, 2 November, 9:20am MT

**Comment by mbrakken** [comment]
@acecarruthers can you try again? I made some updates, and I think it should work now.

I'm also going to create an issue in the API to add some checks around user-based operations, which are in league with user management work I have in progress.

**Comment by acecarruthers** [comment]
@mbrakken The jury tool is now accessible and the reports page is accessible - thanks!  

The artist/album page editor is not accessible yet http://submissions.capitalcityrecords.ca/review-and-publish/submissions/ - should there be a new URL for this?

**Comment by mbrakken** [comment]
Hmm. I was just able to sign in as you there. Those interfaces are not yet
moved into the proper app but that is planned as part of this submission
round.

I'll email you a url outside of Github that should work for you.

**Comment by mbrakken** [comment]
@acecarruthers confirmed she can access. Closing.
