### ISSUE TITLE
Submission interface, round 2

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#161]
Pulled from #128. Most of the conversation in that thread relates to work on this issue. I'm not copying most of that over since it's mostly no longer relevant.
__________
Artist Submissions http://submissions.capitalcityrecords.ca/submit/

Bugs from prior version that need to be addressed:
- [x] not all audio files uploaded successfully so jury wasn't able to listen to all tracks (I believe this is fixed, but we need to test)
- [x] Collect track duration data
- [x] standardize how artists declare they don't have a label
- [x] No need to include artist social media fields incl. YouTube, social media, website at this stage

**Comment by mbrakken** [comment]
Currently deployed. I will remove ALAC as an option, which should resolve all current upload / playback complications.

I also have yet to upload an archive of the original, non-transcoded file, but feel like that's not a blocking concern at the moment.

**Comment by acecarruthers** [comment]
Hi @mbrakken I'm about halfway through the tests I'd like to do on the submission tool and I've encountered a few bugs. I thought I should tell you about them sooner than later.


- Two times I tried to upload an AAC file and it did not play back in submission tool or in the jury tool. In the jury tool, the file had no length associated with it. (In jury tool see Test Album Name 2, the song is 01 Spires That in the Sunset Rise and Test Album Name 4, the song is 02 Spires...)

10:50, 11:20, Firefox 41, Windows 7, Nov 6, 

- FLAC file did not play back in submission tool. After I submitted it, the FLAC file still didn't play in the jury tool, but it did have a length associated with it. (see Test album title 6, song 12 Venus in Furs)
-In the same test, I uploaded an MP3. It played back with no trouble in the submission tool, but did not play back in the jury tool (song: Miley!)

Noon, Chrome 46.0.2490.80, Windows 7, Nov 6

For the most part it was super slick and worked great.

**Comment by mbrakken** [comment]
Hmm. Are these some of the same files we were testing with last time? I
recall that the particular FLAC files used for testing last round behaved
differently from others (including artist-uploaded ones).

The AAC / M4A file I used for testing was an itunes purchase. It's possible
that there's something unique about the one you're using to test.

Any chance you could pass the test files to me, via gdrive, dropbox, etc?

I'm also *hoping* to get archiving of the original, non-transcoded file set
up, but I'd prefer to treat that as non-blocking for the moment.

**Comment by acecarruthers** [comment]
You're right, they are the same files I was testing with last time. I downloaded the FLAC and AAC files from Yahara Music Library and the MP3 I got from EPL's other free music service, Freegal. You can find all the files I've encountered trouble with at https://drive.google.com/open?id=0B56HcVGi1B3nVHoxbGEzTk44X00

**Comment by acecarruthers** [comment]
@mbrakken I have just retested with aac, mp3 and flac files downloaded from Capital City Records and they all work great. Do you know what the problem is with the other files? I can't think of why there would be something weird about them.

**Comment by mbrakken** [comment]
@acarruthers I don't know off the top of my head, but I plan to run them
through the transcoder to see what it reports.

**Comment by acecarruthers** [comment]
OK. I have finished all the testing I planned on and I only found one other bug and it is small. Here is the little bug:
- When I pressed "click to select files" the directory had greyed out aac, ogg and flac files so I couldn't upload them. I think it is just a safari thing. 

Safari 9.0.1, MacBook Pro, OS X Yosemite 10.10.5, Nov 6, 3:50pm MT

There are some text edits I'd like to see in the submission tool, and then we are good to go! Woo hoo!!
https://capitalcityrecords.ca/submit  
- [ ] New Title: Submit to Capital City Records!

- [ ] Add under the title: We are looking for the next 50 artists to join the Capital City Records collection! Have you produced an EP or full length album in any genre in the last five years?  Do you live or regularly perform in the Edmonton Capital Region? We definitely want you to submit! The submission period is open from Nov 12 to Dec 3, 2015.

- [ ] Under Legal Stuff: Change "EPL's Confidentiality Policy" to "EPL's Privacy and Confidentiality Policy" and change the link to http://www.epl.ca/sites/default/files/pdf/board-policies/privacy_and_confidentiality_of_customer_info_b-2005.pdf 

- [ ] Please replace the license agreement that you link to with this one: https://drive.google.com/open?id=0B56HcVGi1B3nTDZlQjlucVg0enM We've corrected some weird numbering in the text.

**Comment by acecarruthers** [comment]
Oh, oops. Just a few more:
On https://capitalcityrecords.ca/submit/album-data 

- [ ] could you make the text in the fields a little lighter in Chrome and Safari? e.g., "July 2012" and "you@youremail.com" should be easier to distinguish from "Independent" and other fields when they are filled in. 
- [ ] change "Artist bio" to "Short artist bio"
- [ ] please remove ALAC from the list of preferred filetypes

On https://capitalcityrecords.ca/submit/thankyou 
- [ ] Please replace the license agreement that you link to with this one: https://drive.google.com/open?id=0B56HcVGi1B3nTDZlQjlucVg0enM (as above)

On https://capitalcityrecords.ca/admin/jury 
- [ ] add the record label name to the jury screen

**Comment by mbrakken** [comment]
Everything checked off is queued to go out with the change in #166. Let me know if you'd rather these go out now instead of then.

I'm managing everything jury-related in its issue, #151.

**Comment by mbrakken** [comment]
The grayed out files in the selector is possibly related to this: https://code.google.com/p/chromium/issues/detail?id=478128

The files can still be dragged and dropped. Currently on the file input I have set `accept="audio/*"`. I could remove that so anything can be accepted by the built in widget and just rely on my processing code to reject files of the wrong types (this is already in place to handle drag & drop).

**Comment by acecarruthers** [comment]
@mbrakken it is fine for all of these changes to roll out at the same time as #166. Don't worry about changing the file input, not a lot of people use Safari, and as you say, they can still drag and drop. What we can do is change some text on the FAQ page:
https://capitalcityrecords.ca/faq 
Can you please completely replace what is currently there with:


We prefer FLAC, WAV and AIFF files. So send us your CD rips or master files at 16-bit 44kHz CD quality or better. These are lossless file types and will sound the best. 

MP3, AAC and Ogg Vorbis will also be accepted, but they will experience more quality loss when transcoded for playback (i.e. to highly trained ears, they won't sound as good). 

Having trouble selecting FLAC, AAC and Ogg files in Safari? Try dragging and dropping the files or switch over to Chrome or Firefox.
