### ISSUE TITLE
artist license interface 0.2

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#163]
Ported relevant bits from #128 
_____________
prior url: http://submissions.capitalcityrecords.ca/complete-submission (requires auth token)
future url: TBD

- [x] We encountered a problem last time (artist couldn't upload her banner image) because the tool didn't support submissions for multiple albums from a single artist. It is likely that we will receive new submissions from artists who submitted last time, so we will want to test that it works all the way through.
- [ ] Recommended maximum size or recommended dimensions for images/ability to select image thumbnails in submission form.
- [ ] Add in image crop / thumbnail selection

Should be mostly portable from prior version. We may want to namespace these under artist names in some fashion, so that an artist can see all their things easily, as well as identify needs.

Really this should turn into an interface for an artist to manage their content, with appropriate accommodations for updating existing content / media. Some of this will require updates on the API.

**Comment by acecarruthers** [comment]
I'd like to send invitations to artists on January 8. Can you estimate when this could be ready for testing? The holidays make it kind of awkward. Is before Christmas possible?

**Comment by acecarruthers** [comment]
@mbrakken, Is it possible to add two additional fields to the artist information page? I've mocked it up below. I'd like people to be able to check either, both or neither box. Since August I've been fielding lots of requests from different departments at EPL interested in showcasing CCR artists. I'd like to narrow down who I consider. 

![live shows](https://cloud.githubusercontent.com/assets/7355887/11159960/ae011238-8a21-11e5-9ab7-f863b84d1c16.png)

**Comment by acecarruthers** [comment]
Hi @mbrakken I've reviewed this interface twice now - once in Firefox and once in Chrome. Overall it is working as it should and looking great! There are some mostly small changes to the UX I'd like to see listed below with the most significant fix at the end:

Artist information page
- [ ] Delete text in banner image upload that says "(We're going for something like this)"
- [ ] Please change social media text (currently below text box) to "Where else can people find you (CD Baby, bandcamp, Twitter, Facebook etc.)"
- [ ] Can the social media text go above the text box as it was last time? As it is now it is unclear what it is referring to.
- [ ] Comment above in GitHub requested two additional check boxes. Is it possible to include this?
- [ ] Change confidentiality policy link to http://www2.epl.ca/public-files/policies/board-policies/privacy_and_confidentiality_of_customer_info_b-2005.pdf

Album information page
- [ ] The way the page indicates that album cover art is being uploaded is a little confusing. As far as I can tell, everything works fine in the end, but the user experience is not great. It was the same for the banner upload too. I took a little video of what I mean and posted it here: https://drive.google.com/file/d/0B56HcVGi1B3nV1RPSXBuV0xEb00/view?usp=sharing if it is possible to avoid the long pauses or the moment when the image disappears, that would be ideal. 

Upload Tracks
- [ ] Delete "aac" from list of accepted filetypes

License Page
- [ ] Accepting the license should take the user to the confirmation screen and they should receive a confirmation email (I should also receive a confirmation email). The only thing that happened was that a message appeared at the bottom of the screen that said "You have already accepted this license." Do you still have access to the text of the confirmation screen and confirmation email from last time? If not, I will try to scrounge it up. Let me know.

**Comment by mbrakken** [comment]
Quick question @acecarruthers : 

Above I say we should pull image cropping / thumbnail selection into the artists' interface. Can I, at least for this round, relegate that to the library's publication process (as it is in the last version of everything).

**Comment by acecarruthers** [comment]
@mbrakken yes no problem

**Comment by mbrakken** [comment]
Updates for the above are out, @acecarruthers. I'll keep this open until you've reviewed.

**Comment by acecarruthers** [comment]
Thanks @mbrakken! Everything is looking good! I noticed two things in the confirmation email:
-  The release date for the album titled "Test album title 6" appears in the confirmation email as "undefined" - but the field is required and I remember there being a date in there. 
- The "I'm interested in playing at.." responses do not appear in the confirmation email. I 100% forgot to request that this information appear in the confirmation email, but I believe it would be useful for me if it appeared there. If this takes a ton of time and might prevent us from sending out invites this week, then don't worry about it.

**Comment by mbrakken** [comment]
Missing release date was a small type. Added the `I'm interested in playing at` part now. I'd meant to do so originally...

About to deploy these.

**Comment by acecarruthers** [comment]
@mbrakken everything is working perfectly! I am going to send out the invites now. Thank you!

**Comment by mbrakken** [comment]
Whooo!
