### ISSUE TITLE
publish interface v 0.2

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#164]
- [ ] sort fall 2015 & prior round in publish interfaces (easily id what's
new for review)

Should be mostly portable from prior version.

**Comment by acecarruthers** [comment]
Reviewing the submissions so far I can see that a number of musicians who are already on Capital City Records have submitted excellent candidates for the next round. Thought we should be aware of the possibility of having to publish second albums to existing artist profiles.

**Comment by mbrakken** [comment]
Cool. That's a case I definitely want to be able to handle. Good to hear
the round is going well :)

**Comment by acecarruthers** [comment]
@mbrakken I know you can probably see the submissions too, but there are 28 so far! In 5 days! I think it is great. I am very happy with how they round is going so far :)

**Comment by mbrakken** [comment]
I haven't actually checked in to see submissions, but with 28 in 5 days and
no major bug reports, I'm pleased as punch :)

**Comment by kellyhiser** [comment]
Pending work (will confirm with Marc today):
- [ ] testing
- [ ] data migration 
- [ ] edge cases
