### ISSUE TITLE
Revisions to Homepage & About Page For Launch

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#166]
On Nov 12, as early as you can (9-9:30 am Central), please make the following changes:

On https://capitalcityrecords.ca/about
- [x] At the end of the first paragraph are the words "call for submissions" - please change this link to https://capitalcityrecords.ca/submit
- [x] Under the Participate heading, please replace "Our next call for submissions is tentatively scheduled for Fall 2015." with "We will run a couple calls for submission each year."

On the homepage
- [x] make the banner below the first image in the carousel so it is the first thing people see on the site. And add the following three lines of text on top of the image:

Call for Submissions Now Open!

Get your album in Capital City Records

SUBMIT

![ccr_music_submissions_ccr_artbox_980x450_nov2015_v2_cs5 2](https://cloud.githubusercontent.com/assets/7355887/11011232/3ec1d3e0-84a3-11e5-9347-1124fdd5c513.png)

The Submit button should link to https://capitalcityrecords.ca/submit 
Is there any way to preview how this will look? If the text and the image are weirdly spaced, I can edit the image to fit better. 

- [x] Add a link to the submission form to the navigation bar. This is kind of what I'm thinking, but if you think there is a better place, that is cool too. 

![nav bar](https://cloud.githubusercontent.com/assets/7355887/11011369/787b69a6-84a4-11e5-903f-78283c7422d2.png)

**Comment by mbrakken** [comment]
@acecarruthers 
![screen shot 2015-11-09 at 12 07 37 pm](https://cloud.githubusercontent.com/assets/1530955/11042271/c0449af8-86db-11e5-9720-43310d5e7cdb.png)

**Comment by mbrakken** [comment]
All this is queued up along with changes in #161.

**Comment by acecarruthers** [comment]
Thanks for the screenshot. Can you replace the carousel image with this slightly revised image. I think the spacing will work a bit better. 

![ccr_music_submissions_ccr_artbox_980x450_nov2015_v2_cs5 3](https://cloud.githubusercontent.com/assets/7355887/11049200/ffd0a86a-86f9-11e5-9934-1c858a4216ce.png)
