### ISSUE TITLE
Dec 4 - Close Submissions

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#171]
As early as you can on Dec 4, please
- remove the link to submit from the homepage nav bar
- remove the submission banner from the carousel
- change the text on capitalcityrecords.ca/submit to "Submissions are now closed. The next call for submissions will be announced in 2016."

**Comment by acecarruthers** [comment]
@mbrakken @nagapampa Submissions are closed today. Can we make the above changes today?

**Comment by mbrakken** [comment]
I've closed submissions, and also stubbed out a way that submission open /
close can be defined by admin configs. Eventually there'll be a process
where you can just define submission rounds, open/close them from an
interface.
