### ISSUE TITLE
Tracks lengths for some submissions not collected

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#172]
Everything plays fine. This isn't a big issue, just thought I should mention it. 

https://capitalcityrecords.ca/admin/jury/rattle-rattle-set-traps-1447726568232

https://capitalcityrecords.ca/admin/jury/rebecca-lappa-tattered-rose-1447636730652

https://capitalcityrecords.ca/admin/jury/consilience-walking-through-a-dead-night-ep-1447641915420 

https://capitalcityrecords.ca/admin/jury/endivera-shameless-1447688597828

**Comment by mbrakken** [comment]
Hmm. Interesting. I'll take a look at it, see if I can figure out why
durations didn't get set. In theory, it should be easy to get duration
later in the process for any that didn't initially get set.

**Comment by kellyhiser** [comment]
moving to #197 and closing
