### ISSUE TITLE
Cannot load albums, artists, posters or jury, publishing pages

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#174]
Hi @mbrakken 
the homepage looks like this (for example)
![error message_nov26](https://cloud.githubusercontent.com/assets/7355887/11430646/f6c241c0-9446-11e5-8a36-3a4d97b14738.png)

Submit, About and FAQ pages work, so does the reports page. 
Noticed ~2pm MT Nov 26 tested on Firefox 42.0 and Chrome 46.0.2490.86, Windows 7,

**Comment by acecarruthers** [comment]
scary update: The jury page resolved, but listed no submissions.

**Comment by acecarruthers** [comment]
@prestonaustin @kellyhiser @mbrakken any updates on this?

**Comment by jjg** [comment]
Resolved.  API server CPU was pegged, need to do more analysis to determine the cause.  Resolution was rebooting the API server.

**Comment by mbrakken** [comment]
Closing.
