### ISSUE TITLE
Glitchy track

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#182]
This track keeps stopping and starting. https://capitalcityrecords.ca/admin/jury/althea-cunningham-on-the-verge-1447886262982

 I have noticed this on other tracks, but only in Firefox and it has never been consistent. This track keeps starting and stopping in both browsers every time I play it. 

Could this be a problem with the upload process or is it inherent to the file?  
If I asked the artist to email me a new file, would we be able to replace the one here?

 ~5:20pm MT, Dec 15, on Firefox and Chrome.

**Comment by jjg** [comment]
Hey all, can one of you assign this to me please? I can't seem to do that on my phone :)

**Comment by jjg** [comment]
Can you set me up with a login?  Thanks!

**Comment by mbrakken** [comment]
@jjg I can send you my credentials.

**Comment by jjg** [comment]
Is it normal for the URL to indicate the file is mp3 when the stored media is wave?

**Comment by jjg** [comment]
I think I got to the bottom of this, please test and let me know if it continues to be a problem :)

**Comment by acecarruthers** [comment]
@jjg I've tested it and it sounds good. Thanks! Is there a chance that the error you fixed could have affected other tracks?

**Comment by prestonaustin** [comment]
Yes, but we can't identify which ones. It was a server load distribution
problem not a data problem, so the fix would fix anything impacted.

-- 
Preston Austin - @gl33p

**Comment by acecarruthers** [comment]
Thanks Preston, that is good news
