### ISSUE TITLE
Login not responding to customer card # and pin

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#187]
Have received two customer reports of download buttons and login button not working. I am unable to replicate. 

Here is how they describe the issue:

"I have tried to log in to Capital City records, but the login button does not work on Chrome or Firefox on my computer, I can input my card number and password but when i click "login," nothing happens." 

Customer 1, Windows 8, desktop, Chrome  47.0.2526.111, Jan 16, 2016, 11:14AM 

"I go into the database and clicked on albums, then clicked on an album. The track list comes up and I'm able to stream songs. When I click on add to your collection, a log-in page comes up, but when I enter my info and press submit, the page seems to freeze.
The same thing happens when I click on the login link."

Customer 2, Windows 7, desktop, Chrome 47.0.2526.11, Jan 18, 2016, 9:50AM

**Comment by jjg** [comment]
@acecarruthers do we know if these are people who have used the site before?

**Comment by acecarruthers** [comment]
@jjg I just confirmed that customer 2 has never logged in successfully in the past. I suspect customer 1 has used the site before - Customer 1 was the person who wrote about having similar trouble in issue #183

**Comment by jjg** [comment]
Thanks for the info.  Just did a spot-check on the various back-end systems and things look normal.  If we can find a way to re-create the error, I can try to debug it.

**Comment by acecarruthers** [comment]
I can probably get you a screen shot of the developer console for customer 2. She works here. If that would be useful, let me know how you'd like her to set it up.

**Comment by jjg** [comment]
Yes a screenshot that includes the javascript console output (especially if it displays an error) would be a good start.

**Comment by acecarruthers** [comment]
![login error_jan18](https://cloud.githubusercontent.com/assets/7355887/12398578/e13f577a-bdd1-11e5-8d8e-50ade67a3b94.png)

**Comment by acecarruthers** [comment]
She tested this three times from the home login, the "add to your collection" button and by trying to download an individual track and she says she received the exact same message. Though she adds:

"the first times I tried to login there was a slightly different error message: https://ccrapi3.murfie.com/auth/users/2d3ca9f1426c54777158a60ad006126539f82713 Failed to load resource: the server responded with a status of 401 (Unauthorized) 
And: vendor-e8748835318d1cf7396dcd95b71152bb.js:10 Uncaught TypeError: Cannot use 'in' operator to search for 'finished' in null   

These errors were above and below (respectively) the "not a function" error message."

**Comment by acecarruthers** [comment]
Customer 1 just let me know that clearing his history and cache made no difference. He is still unable to access downloads.

**Comment by mbrakken** [comment]
This should be resolved now. Please let me know.

**Comment by acecarruthers** [comment]
Customer 2 is able to log in! Yay! thanks! I'll close this when I hear back from customer 1.
