### ISSUE TITLE
Artist Can't Upload New Tracks

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#188]
Josh Sahunta was not able to upload any additional tracks to his album. Here is how he describes the issue: 

"I was having an issue uploading more than 1 song. The loading bar would would not disappear and I had to keep refreshing the page only to have the same issue repeat itself. I even shut off my computer's sleep function to see if maybe the loading actually did need more time but even after an hour it was still there. I was uploading using Google Chrome on a Mac OS 10.11.2 El Capitan."

He ended up signing his license and finishing the submission process with just the one song. The only track that is currently uploaded is the one he included in his initial submission. In order for him to try again we'll need to unsign his license somehow or create a new submission form for him. 

He was working on this Jan 16, between 3:00-4:30PM

**Comment by mbrakken** [comment]
@acecarruthers, can you ask Josh to email me one of the tracks he was
trying to upload? It'll help me figure out why his tracks weren't uploading
cleanly.

Un-signing the license should be easy.

**Comment by acecarruthers** [comment]
New message from Josh (Feb 3):
"Just wanted to let you know that I successfully uploaded the rest of the songs (there should be 6 now). Please let me know if they came through alright and if theres anything else I can provide!"

I have not received a confirmation email and his tracks do not appear on the albums data page.
