### ISSUE TITLE
Artist can't upload album

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#191]
Message below received from Wilfred Kozub on Thursday, January 28, 2016 2:44 PM. I believe this might have something in common with #189 

A few days ago I was adding information about my album, What's Gonna Become of Us by Wilfred Kozub, to  your website. When I got to the part where I upload the music, I ran into a problem. I uploaded the first track, "Drag Your Feet Over," and that seemed to work properly. Before it was fully uploaded, I started the uploading of the second track, "Maybe I'm The Only One".  I got some sort of error message and, very briefly, I think there was a flash of a message asking me to contact administration. Before I had a chance to actually read it, the message was gone.

I had to put the uploading of my album aside for a few days while I was working on a grant application. 
Today I went back to my page on Capital City Records to continue, and I don't seem to be able to access either of the songs that I had tried to upload. My songs are being uploaded as WAV files.

Is there a way of resetting the album upload part of my application. I don't mind starting all over with this. Can you suggest how I should proceed?

**Comment by acecarruthers** [comment]
Wilfred adds:  I was using Firefox when I was trying to upload my music. I'm on an iMac and I'm running Max OSX (version 10.6.8)

**Comment by acecarruthers** [comment]
It appears that the Pigeon Breeders are having a similar issue. Here is what they said "we were in the process of putting up our "Oblique Temperatures" album and information on Capital City Records. We were having troubles with the server and/or the last .WAV file and now it appears that the server is down. All we needed was to get one more track successfully uploaded and agree to the license in time for February 3rd."

**Comment by acecarruthers** [comment]
New message from Josh:
"Just wanted to let you know that I successfully uploaded the rest of the songs (there should be 6 now). Please let me know if they came through alright and if theres anything else I can provide!"

I have not received a confirmation email and his tracks do not appear on the albums data page.

**Comment by acecarruthers** [comment]
Update from Wilfred after being invited to try again:

I just tried uploading the second song on my album, Maybe I'm The Only One. For just a moment, it looked like it was
going to work. Then there was a message in red that flashed on and went off before I could read it, but it said something
to the effect of "problems uploading . . . contact administrator". Maybe it's a simple fix at this point?

The "Upload Tracks" page shows the song in position 2 and shows "Uploading 42.2 MB" but nothing is happening.

I made a copy shot of my screen and I've attached here so you can have a look.
![wilfred s upload screen_march8](https://cloud.githubusercontent.com/assets/7355887/13620805/c6483400-e54f-11e5-8f7d-f8bacf0b79b2.png)

I also tried playing my file and it works fine. I've uploaded my songs successfully to a number of websites.

**Comment by kellyhiser** [comment]
I'm consolidating all open issues related to track upload here. Here's a summary of what I believe is extant: 

1. Wilfred Kozub unable to upload tracks, receiving brief flash of error message like: "problems uploading . . . contact administrator" Firefox, iMac, Max OSX (version 10.6.8) .WAV
2. Pigeon Breeders unable to load final track of their album .WAV
3. Brother Octopus unable to load final track of their album, progress bar freezes. iMac OS X Yosemite (previously #189 ) 
4. Rattle Rattle unable to upload tracks (previously #195 )
5. Dub Vulture unable to upload tracks, receiving unspecified error message (previously #193 )

@acecarruthers can you confirm that this list includes all open track upload issues?

**Comment by acecarruthers** [comment]
There are three additional open issues related to track upload in some way. I'm not sure these are the same issue as above:
- [ ] Bong Sample uploaded their album and signed their license without apparent trouble, but tracks 4 and 11 of the album did not upload (previously #192)
- [ ] Choir and Marching Band uploaded their album and signed their license without apparent trouble, but only 3 out of 17 tracks successfully uploaded  (previously #192)
- [ ] Kaz Mega's uploads froze when he tried the first time and he wasn't able to delete and re-upload.

**Comment by kellyhiser** [comment]
Okay, I'm going to pull one more note from #192 and then close that so that all missing tracks/track upload issues are here. That note is:
- [ ] Update: I can play back Lindsay Walker's track 1 "Try (all fall down)" in the admin Complete Submission interface, but I don't see a URL or access token at the endpoint here https://ccrapi3.murfie.com/review-and-publish/albums/fall-2015/?auth=

**Comment by kellyhiser** [comment]
Alex's priority list for these issues and summary of steps taken: https://docs.google.com/spreadsheets/d/1pZvAFK3a1QlybiD0EsaDSNzHj2O-6-tXbTPV9kHw28w/edit#gid=1660484850

Endpoints with artist, album, contract data (accessible only to Preston and Kelly): https://docs.google.com/document/d/1xPMD-JAqLMcoaF2YWc6Ni61fDATMN7IkL5aDmEaS2Mw/edit
