### ISSUE TITLE
Missing tracks in completed album submission. 

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#192]
Only three of the 17 tracks listed as part of Trevor Rockwell's (Choir and Marching Band) album appear to have uploaded. There are no URLs associated with his tracks on this page: https://ccrapi3.murfie.com/review-and-publish/albums/fall-2015/?auth=
**NOTE i removed the auth token in this URL to keep it private. Let me know if you need me to email it to you. This is the same page I am talking about in #194)

Trevor has accepted his license and confirmed all the details. Can you suggest a next step @mbrakken?

**Comment by acecarruthers** [comment]
Have noticed missing tracks in other albums, but none to the same degree. They are 

track 4, Midnight Oscillations by Bong Sample
track 11, Through the Light by Bong Sample
track 1, Try (all fall down) by Lindsey Walker

**Comment by acecarruthers** [comment]
Lindsey Walker has uploaded her full album successfully, but reported trouble uploading mp3 files. She was only able to upload a WAV file.

**Comment by kellyhiser** [comment]
Update: I can play back Lindsay Walker's track 1 "Try (all fall down)" in the admin Complete Submission interface, but I don't see a URL or access token at the endpoint here https://ccrapi3.murfie.com/review-and-publish/albums/fall-2015/?auth=

**Comment by kellyhiser** [comment]
all above issues moved to #191
