### ISSUE TITLE
Artist link won't resolve

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#193]
Artist Dub Vulture hasn't been able to open the link sent to them in their invitation email. They have tried a number of times. It loads and loads and never opens. (I have successfully opened it in every browser and on every system I have access to). I asked for more details including browser, OS, time and date. Will update here when I hear back. 

This is the link: https://capitalcityrecords.ca/admin/complete-submission/dub-vulture-robocalls/artist?auth=d9cbd0e3284ce1e721e1e3fb6f603c56030ef6d2

**Comment by acecarruthers** [comment]
Here is the artist's response:

"I've tried to open the following link last night and this morning on two separate Macs both with Safari and the newer one running OS X 10.11.3 :

https://capitalcityrecords.ca/admin/complete-submission/dub-vulture-robocalls/artist?auth=d9cbd0e3284ce1e721e1e3fb6f603c56030ef6d2.

I only get a "failed to open page" notice from the browser."

**Comment by mbrakken** [comment]
Ahh, yeah. This totally sounds like it's from DNS being out.

**Comment by acecarruthers** [comment]
Oh that is good news. I let the band know. I'll close this when I receive their completed submission. Thanks!

**Comment by acecarruthers** [comment]
Here is Dub Vulture's response:

"I was able to get into the registration page, but I repeatedly got error messages whenever the wave files were being uploaded.  Eventually, after the third try, the Upload Tracks page itself failed to load."

**Comment by acecarruthers** [comment]
Update from Dub Vulture (Tim Balash):
"I'm sorry to report that I'm still unable to upload tracks.  An error alert came up when I selected the first song."

**Comment by kellyhiser** [comment]
Moved upload issue to #191 - closing.
