### ISSUE TITLE
Upload Tracks Page Going Blank

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#195]
on Tuesday Feb 2 at 7:44pm the band Rattle Rattle wrote 

"it is unclear to me if our full album tracks have successfully uploaded to the Capital City Records site. The license agreement correctly states the file names (good sign), but the Upload Tracks page has gone completely blank so I am unable to listen to the tracks to confirm their upload (bad sign).

How should we proceed?"

**Comment by acecarruthers** [comment]
Update from Rattle Rattle on March 8th. 
"I've tried to upload Rattle Rattle files again, and there's both good news and bad news.

The good news is that the upload page is visible. The bad news is that when I attempt to upload a file, it returns an error message, prompting me to contact support."

**Comment by kellyhiser** [comment]
I moved the upload issue to #191 
It looks to me like @mbrakken fixed the bug causing the blank upload page, so I'm closing this issue. @acecarruthers or @mbrakken please reopen if that's wrong.
