### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#196]
At 4:59 on Tuesday Feb 2, Artist Kathleen Yearwood is receiving an error report when she tries to playback the songs she has uploaded. She writes "I just uploaded everything at the local library- they do play but I sometimes get an error report- can you make sure it's all okay?"

**Comment by acecarruthers** [comment]
I have listened to Kathleen Yearwood's tracks that have appeared on the albums data page and they all work. It might be worth while to confirm that the tracks that appear are all the tracks she wanted to upload. I have listed them below in the order she has given them.

 I have not received a confirmation email for her submission. Has she signed her license agreement? 

- L'on dit q'amors
- St.Pauls Infirmary
- Ã€ La Claire FantÃ´me
- Rue des Blancs- Manteux
- Riels Letter
- Remember Love
- Anniversaries
- God Wasn't There
- Crowfoot

**Comment by kellyhiser** [comment]
@acecarruthers do you want me to contact Yearwood to confirm the track listing here? Happy to do so. I just confirmed that she did sign a license. Let me know, and then I'll close this and move submission email confirmation to #194

**Comment by acecarruthers** [comment]
@kellyhiser I have confirmed the complete track listing with Kathleen. Everything is good here. I have been keeping track of issues in a Google Drive Spreadsheet because I was having trouble keeping things straight in GitHub. I will make sure everything is consistent between the two places. https://docs.google.com/spreadsheets/d/1pZvAFK3a1QlybiD0EsaDSNzHj2O-6-tXbTPV9kHw28w/edit#gid=1660484850
