### ISSUE TITLE
Time Sensitive - Please confirm details

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#198]
On both the data page and the "complete submission" page there are 4 albums with working tracks and licenses marked "signed" that I have not received confirmation emails from. The artists are Kathleen Yearwood, Politic Live (Marlon Wilson), Josh Sahunta and Raani (Danny Fournier).  

Is there a chance that these musicians have received confirmation emails even though I haven't? If so, the confirmation email has told them they can expect to be paid in 10-12 business days and I want to make sure they get their money on time. 

@mbrakken For each of the artists, can you confirm whether or not they have signed their license agreement and can you please send me their mailing addresses?

**Comment by acecarruthers** [comment]
I have sent Kathleen Yearwood, Marlon Wilson and Danny Fournier their honorariums. 

I am waiting on Josh because the url endpoint shows that he signed his license on Jan 16, which is before he uploaded most of his tracks. The license that is visible on https://capitalcityrecords.ca/admin/complete-submission/josh-sahunta-i-d-leave-my-happy-home-for-you shows an agreed to license with all 6 songs. 

If there was some contention about Josh's license a year from now, would we be able to produce evidence that his license covers all 6 songs?

**Comment by kellyhiser** [comment]
@acecarruthers, I believe that you could produce the license you're seeing in the submission interface as proof. Is your concern that he signed the license believing he was licensing fewer tracks, then added tracks, and the system retroactively included those tracks in the license? I'm not sure whether that's possible.

**Comment by mbrakken** [comment]
I'm currently putting together an update to allow artists to easily re-sign
licenses. I hope to have that all together today at some point and will let
Josh know that he can re-sign it.

**Comment by acecarruthers** [comment]
Thanks @mbrakken! Thanks for following up @kellyhiser, It looks like Josh agreed to the license once he had uploaded all 6 tracks, but the wrong date was automatically assigned to the license. That discrepancy was making me a wary, though practically it maybe that isn't such a big deal in this case. I think having Josh re-sign the license will solve this nicely.

**Comment by mbrakken** [comment]
Yeah, affordances for re-signing have always been part of the plan. I'll
still need to decide how I want to handle presenting the updated license to
the stage that follows (review & publish), but that fits in with some of
the second-round wrinkles I've been strategizing about this week.
