### ISSUE TITLE
Two Wilfred Kozub tracks failing to upload

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ccr-app#204]
Wilfred had issues with upload previously, so I uploaded files on his behalf this morning, using .wav files he shared via dropbox. 

I successfully uploaded his entire album (18 tracks) with the exception of two tracks: track 2 MaybeImTheOnlyOne and track 10 The Weather (Don't Like It).

With both tracks, a progress bar appeared, and then shortly after so did an error message telling me to contact admin. Both tracks continued to look like this as I added other tracks:
![screen shot 2016-03-18 at 10 18 14 am](https://cloud.githubusercontent.com/assets/8515447/13887787/0c08cf2e-ed14-11e5-9cbb-f84b3490740a.png)
Clicking delete did not get rid of the tracks in the interface and did not produce the usual confirmation message (“do you want to delete” or whatever it is), although when I refreshed the page, the tracks disappeared.
Chrome, around 10:20 AM ET 18 March. Replicated this behavior in Firefox 2:22 PM ET 18 March.

@prestonaustin I shared the two tracks in question with you via dropbox.

**Comment by kellyhiser** [comment]
I should add - I think there are separate issues here: the kind of feedback the system is giving users and the actual failures. I'll be adding the feedback issues to other bugs we need to fix but that aren't blocking for this submissions round.

**Comment by prestonaustin** [comment]
@kellyhiser Please also share the tracks that worked with me (all of them)
so I can compare files for differences to triangulate what drives the fail
if it isn't obvious. I'll delete them all from Dropbox when we close this
issue out.

**Comment by prestonaustin** [comment]
"dash in the file name was not a utf-8 dash" - worked around, closing.
