### ISSUE TITLE
I accidentally published an artist page too early

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#211]
Specifically switches 
Admin side: https://capitalcityrecords.ca/admin/review-and-publish/submissions/artists/switches 
Public side: https://capitalcityrecords.ca/artists/switches 

Can someone unpublish them? 
(BTW, the page looks great!)

**Comment by kellyhiser** [comment]
Well, that's one way to test :) Preston is going to take a look at this first thing today.

**Comment by acecarruthers** [comment]
No need to bother with this if we are launching soon :)
