### ISSUE TITLE
Please revise text on CCR carousel to announce new collection

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#215]
Rather than send you a new image and text for the CCR carousel announcing the launch, I think it would be simplest if we just changed the text on one of the existing carousel images. 

Can you please change the text that currently says 

Capital City Records: Edmonton Local Music
Just What Are We Trying to Do Here?
More

TO:
New artists! New albums! 
New Edmonton music to stream and download for free 
Listen 

Thanks!

**Comment by prestonaustin** [comment]
I tihnk https://github.com/therabble/ccr-app/pull/225 will close this. @mbrakken please reopen if I'm wrong.
