### ISSUE TITLE
Rattle Rattle tracks not saved properly and license signing weirdness

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ccr-app#217]
Looks like Rattle Rattle's tracks were not included in the backup used for the latest CCR reboot on 4/19. 

Album record here: https://capitalcityrecords.ca/admin/complete-submission/rattle-rattle-set-traps/tracks 

Album WAV files in dropbox folder: https://www.dropbox.com/home/CCR%20tracks%20Rattle%20Rattle

Additionally, Alex received a confirmation email that Michael Doyle signed the license for this album, but the email reads "License Accepted: Null" (copy pasted below with addresses removed):

From: Capital City Records [mailto:localmusic@epl.ca] 
Sent: April-19-16 2:26 PM

Subject: Submission Received – Capital City Records
 
Hi Michael James,

Thanks! Your submission to Capital City Records has been received. Your honorarium will be sent to the address you provided within 10-12 business days. We'll let you know when Capital City Records goes live so you can check out your page and the other excellent artists in the collection.

Please review and confirm the information you provided below. If you have questions about any part of this process contact localmusic@epl.ca.

License accepted: null
Include Creative Commons Attribution 4.0 International Public License: null

Licensor information
Name: Michael James Doyle

Artist information:
Artist: Rattle Rattle
Tags: art punk, disaster pop, spoken word, art rock, cello, drum machine, yelling, poetry, punk, garage punk, indie punk, post-punk, alternative rock, garage rock, library of congress, sony leak, poetry, slam, slam poetry
Bio: Produced by Doug Hoyer, Edmonton art punks Rattle Rattle find the fun in every sound and share it with folks like you, who make art fun / make fun art.
Banner image: https://ccrapi2.murfie.com/complete-submission/artists/rattle-rattle/rattle-rattle-set-traps-700x700.jpg
URLS:

Artist website: rattlerattle.bandcamp.com
Social media: facebook.com/RattleRattle780, rattlerattle.bandcamp.com
Video source: null
I'm interested in playing at:
Family events: false
Adult events: true
Album information
Title: Set Traps
Release date: Sat Apr 18 2015
Cover art: https://ccrapi2.murfie.com/complete-submission/albums/rattle-rattle-set-traps/rattle-rattle-set-traps-700x700.jpg
Genre: Rock
Record label: Independent
Tracks

Stadium Drums, 01 Stadium Drums.wav
Shadows of Ghosts, 02 Shadows of Ghosts.wav
Suburbs (kids were supposed to be), 03 Suburbs (kids were supposed to be).wav
Crooked Rumours Crooked Rumours, 04 Crooked Rumours Crooked Rumours.wav
Lightning Crackling Knees, 05 Lightnin' Cracklin' Knees.wav
Red Sky In The Morning, 06 Red Sky In The Morning.wav
Industrial Arts, 07 Industrial Arts.wav
Opportunity Knocks, 08 Opportunity Knocks.wav
Vonnenauts, 09 Vonnenauts.wav
Walking Papers, 10 Walking Papers.wav

**Comment by mbrakken** [comment]
tracks / album published. one track is missing the duration. if I know what account was used to upload that track i can grab the access key and re-upload it to trigger a reanalysis of the track to set the duration

**Comment by kellyhiser** [comment]
leaving this open so that we can check on the license question. @acecarruthers if you haven't paid Rattle Rattle already, I think that you should.
