### ISSUE TITLE
license signing failure 

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ccr-app#219]
Attempted to re-sign license for Lindsay Walker, got the following error: 

Something went wrong, caught exception: Ember Data Request PUT https://api.capitalcityrecords.ca/complete-submission/contracts/fall-2015/lindsey-walker-our-glory returned a 0
Payload (Empty Content-Type)

screenshot of JavaScript console: 
![screen shot 2016-04-25 at 8 21 34 pm](https://cloud.githubusercontent.com/assets/8515447/14803011/c95807e8-0b23-11e6-94bd-4513f18363e1.png)

after this happens, the license was marked "signed" in the left hand panel in the Complete Submissions interface until I clicked out of "Complete Submissions" into "Review & Publish" and then back again, at which point it reverted to "ready"

replicated the above behavior when trying to sign for The Unfortunates. 

@mbrakken do you suggest any more testing?

**Comment by prestonaustin** [comment]
I think the fixes to data in 218 are fixing this too but I don't know. Needs testing IFF these licenses need signing.

**Comment by kellyhiser** [comment]
these licenses do not need signed.

**Comment by prestonaustin** [comment]
We have a maybe-bug here without a now-need, so closing.
