### ISSUE TITLE
some artist pages blank after publishing although thumbnails exists

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ccr-app#222]
namely: 

Dirt Road Angels https://wax.capitalcityrecords.ca/artists/dirt-road-angels
Dub Vulture https://wax.capitalcityrecords.ca/artists/dub-vulture
I Am Machi https://wax.capitalcityrecords.ca/artists/i-am-machi
Politic Live https://wax.capitalcityrecords.ca/artists/politic-live
Rebecca Lappa https://wax.capitalcityrecords.ca/artists/rebecca-lappa
Lindsey Walker https://wax.capitalcityrecords.ca/artists/lindsey-walker

and one album page: 
Politic Live's Ellipsis https://wax.capitalcityrecords.ca/albums/politic-live-ellipsis

I published the above artists and albums; their thumbnail shows up on the artist page, but takes me to a blank page. (All other artist pages published without a hitch)

JavaScript console (second message):
![screen shot 2016-04-25 at 11 46 03 pm](https://cloud.githubusercontent.com/assets/8515447/14806330/faa1fe96-0b3f-11e6-9220-e72048855c68.png)

**Comment by prestonaustin** [comment]
Bad field value issues appear to be making the artist page puke. Fixing fields to work for now. Will work on capturing the vom for better user feedback and developer inspection later.

URL that broke one page: "youtube_url: "http://www.youtube.com/dirtroadangels" on https://api.capitalcityrecords.ca/public/artists/dirt-road-angels?collection=ca.epl.capitalcityrecords
 - [ ] fork an issue to test and fail, drop, or fix these on entry and publishing operations

**Comment by kellyhiser** [comment]
The URL type Preston identifies above broke all other artist pages listed in this issue with the exception of one (Dub Vulture), which had this URL: https://youtu.be/fGeWac9gyT8

**Comment by prestonaustin** [comment]
Note from Marc: look at other afterRender examples, and at http://emberjs.com/api/classes/Ember.run.html#method_scheduleOnce to fix the youtube URL problems.

**Comment by kellyhiser** [comment]
blank website field Politic Live was remaining problem - filled in with their sound

**Comment by kellyhiser** [comment]
all pages are now fixed. moved stable fix to MUSICat: https://github.com/therabble/musicat/issues/6
