### ISSUE TITLE
add ability to fix slugs and paths for artist and album names with errors

### ISSUE THREAD

**Issue by kellyhiser** [therabble/ccr-app#227]
change "Barry Campberll Band" to "Barry Campbell Band"
https://wax.capitalcityrecords.ca/albums/barry-campberll-band-ballad-of-a-ne-er-do-well

**Comment by prestonaustin** [comment]
Fixing display layer but not slugs and paths at this time. We need better methods for that. This issue should remain open until we write them.

**Comment by kellyhiser** [comment]
actually, this issue already exists: #208
