### ISSUE TITLE
Album/artist all images broken

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#229]
I noticed at 2:45PM MT that album covers and artist banners were not resolving. Tested on Firefox 45.0.2

Another EPL staff member noticed the same thing around 3:17PM MT on Chrome.

**Comment by prestonaustin** [comment]
Confirmed, investigating now.

**Comment by prestonaustin** [comment]
Fixed. The caching server is not caching, which means intermittent
interruptions on the processing server are immediately impacting the site.
We're investigating and will fix, as well as adding resources to the
processing node so it can handle it.
