### ISSUE TITLE
Apply fix from seattle issue #102

### ISSUE THREAD

**Issue by whblondeau** [therabble/ccr-app#242]
See [SPL issue 102](https://github.com/therabble/seattle-public-library-client/issues/102): deletion of a bad test album from SPL production hosed a lot of things, because the items were deleted but the index wasn't.

Short-term fix is to harden the serializers where a null value was blowing everything up. This SPL fix needs to be applied to CCR as well.

**Comment by kellyhiser** [comment]
assuming this fix is done because deletion work for NBB is done, and that changes will be applied to all sites in the process of stemification. re-open if I'm wrong.
