### ISSUE TITLE
Image viewable area selection interface

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#25]
can be delivered post beta-launch / Marc's begun but not finished this

**Comment by lahollen** [comment]
Once working, use it to properly thumbnail the following:
- [ ] Wilfred N and the Grown Men
- [ ] Bombproof the Horses
- [ ] Passburg
- [ ] Felt Hat String Band
- [ ] Paul Richey and the Fusionauts
- [ ] No Museums
- [ ] Tyler Butler
- [ ] Dub Vulture
- [ ] TOMBTHEMUSICIAN
- [ ] Choir and Marching Band
- [ ] The Frolics
- [ ] VERA
- [ ] Carrie Day

**Comment by prestonaustin** [comment]
This should most likely wait until after @jjg has had a whack at changes to MMS to support crop, format, precise size, and compression control in client calls. So probably we do this one last.

**Comment by acecarruthers** [comment]
I went through the artist banners/thumbnails that needed revision and recorded the dimensions and coordinates of the new better thumbnails. Some of the artists in the list above ended up being best as they are now. I added a few others. It is all in this spreadsheet:
https://drive.google.com/open?id=1tQZmrZzCi1MopX5n0HkBV8QFzR-X8aIsZYBm8ScJ-8A 

Do you need JPEGs of the cropped thumbnails or are the coordinates and dimensions fine?

**Comment by prestonaustin** [comment]
Cropped .png files at or above the larger display size (in pixels) for the
thumbnails in question would accelerate the work and maximize quality. The
MMS already handles sizing, format, and compression of images, so no need
to compress sources. It's just cropping and aspect ratio adjustments it
isn't currently configured to do.

@jjg @mbrakken jump in if I'm wrong here

**Comment by prestonaustin** [comment]
Will specify the UX after @jjg finalizes the endpoint, reassigning to me until https://github.com/murfie/mms/issues/37 is deployed, then I'll discuss next steps with @nagapampa

**Comment by acecarruthers** [comment]
PNG thumbnails available at https://docs.google.com/spreadsheets/d/1tQZmrZzCi1MopX5n0HkBV8QFzR-X8aIsZYBm8ScJ-8A/edit?usp=sharing

**Comment by mbrakken** [comment]
Quick update here:

This is mostly together in this branch: https://github.com/therabble/ccr/tree/image_crop

I just need to do the calculations on the two corners and save them with the artist record. @jjg has said that he'll likely get to specifying the call parameters tomorrow, so I'm holding off on finishing this until I can make sure I'm storing values that trivially work with the future mms side of the equation. That remaining piece should go fairly quick.

**Comment by prestonaustin** [comment]
@acecarruthers given this I would like to put off fixing thumbnails by one
more day, and do it Thursday. If @jjg and @mbrakken aren't confident
Thursday morning that we can finish this with the provided data, we'll do a
workaround with the provided graphics. Is this OK?

**Comment by acecarruthers** [comment]
sure!

**Comment by mbrakken** [comment]
i'm deploying an update to the admin app to collect crop area data, then I'll go and get that data in for the necessary artist images and update the public app accordingly.

FYI, the interface for getting crops is slapdash, but it gets the job (data) done for now.

I'll close when everything is completed.

**Comment by mbrakken** [comment]
ok. all in https://drive.google.com/folderview?id=0B56HcVGi1B3nfnh5a1BvalEyelF3Ui1GcG1CYWVxblFNWW1ILXYzS0EteU1VanYxeXg0ZGc&usp=sharing have been updated, #106 uses available data in the app. that's now out. closing.
