### ISSUE TITLE
URL: wax.capitalcityrecords.ca

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#26]

**Comment by prestonaustin** [comment]
@jjg Will meet with you on this, or...please just tell me what murfie.com
URLs you are setting up and what you think I need to set up at MUSICat.co
and ask for at capitalcityrecords.ca - we should both search email too, as
we did some of this like a year ago!

**Comment by prestonaustin** [comment]
DNS records are done. @nagapampa can you do Heroku config (check in with Marc and Jason if that's new territory for you - I think you can do it in the app control panel on heroku) and please close this after determining Heroku config changes are live and routing wax.captitalcityrecords.ca name to CCR-public.herokuapp.com is working. I don't think this intersects with @jjg's work on SSL but chime in if it does, Jason.

**Comment by nagapampa** [comment]
http://wax.capitalcityrecords.ca/ is pointing to the latest deployment
![wax](https://cloud.githubusercontent.com/assets/2964839/8583578/3c6e3002-2594-11e5-8c9f-427d97217900.png)

**Comment by nagapampa** [comment]
wax.capitalcityrecords.ca.musicat.co

also points to ccr-public.herokuapp.com

**Comment by jjg** [comment]
Hey all.  Heroku responding to this should be all set (took care of that before making the DNS requests, preemptive strike :)

**Comment by jjg** [comment]
I'll work on binding https to that asap.

**Comment by prestonaustin** [comment]
yep. it works.
