### ISSUE TITLE
embed survey code

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#27]
You can find the beta test code here: https://drive.google.com/open?id=0B56HcVGi1B3nUHJCLUVoSl8tdzA&authuser=0

Here is a video created by fluidsurveys on how to set up popups: http://help.fluidsurveys.com/articles/en_US/using-popups

The video and instructions refer to Prevent Popup Code, which you can find here: https://drive.google.com/open?id=0B56HcVGi1B3nTVRhT1Z2T3VrTnM&authuser=0

**Comment by nagapampa** [comment]
![survey](https://cloud.githubusercontent.com/assets/2964839/8581153/93696d5a-2584-11e5-9c25-dc1ca675f0fe.png)

**Comment by nagapampa** [comment]
This is deployed
