### ISSUE TITLE
display track lengths on album pages

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#28]
@nagapampa talk to @jjg about where the metadata is

**Comment by mbrakken** [comment]
i need to check in with @jjg about this. wip branch for showing playback position here: https://github.com/therabble/ccr-app/compare/position

**Comment by lahollen** [comment]
@mbrakken can you give an update on this ticket?

**Comment by lahollen** [comment]
@jjg do you think you can directly rewrite the metadata for this ticket so that @nagapampa could finish it off without Marc?

**Comment by lahollen** [comment]
@jjg really this question is about #8

**Comment by prestonaustin** [comment]
@mbrakken I'm assuming you are working on this today (monday) please update this ticket end of day if unclosed.

**Comment by mbrakken** [comment]
Will be closed by #94
