### ISSUE TITLE
Track does not play

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#33]
http://ccr-public.herokuapp.com/albums/josh-sahunta-lights
First track Supernova isn't playing

**Comment by prestonaustin** [comment]
@mbrakken What is the "least developer involved" path to replacing a track?
For example: Re-upload, re-sign, and re-publish.

**Comment by mbrakken** [comment]
I'm not really sure there's an easy way right now, given tradeoffs we had
to make when we turned to redis over jsfs for storing json data. There
isn't yet a good way to access or compare diffs when upstream content
changes.

The process I used for Look Away's tracks is the best I can think of right
now, but I'll see if something else comes to me.

**Comment by mbrakken** [comment]
BTW, the PR referenced above takes care of this. It's not a track problem, it's the transcoder's support for m4a. Most browsers will just play m4a, though.

**Comment by mbrakken** [comment]
Also, I can update my process I used. I wrote that first version in a hurry.

**Comment by prestonaustin** [comment]
@mbrakken Post a link to that process here when you can, then close this out and open an issue later about a process for this.

**Comment by acecarruthers** [comment]
Couldn't get the song to play on iPad (Safari, Chrome) or Android phone (Chrome). 

Alex, iOS 8.3, 10 July 4:24pm mt http://ccr-public.herokuapp.com/albums/josh-sahunta-lights
& Samsung Galaxy S6, Lollipop, 10 July, 4:30pm mt

**Comment by acecarruthers** [comment]
Couldn't get the song to play on iPad (Safari, Chrome) or Android phone (Chrome).

Alex, iOS 8.3, 10 July 4:24pm mt http://ccr-public.herokuapp.com/albums/josh-sahunta-lights
& Samsung Galaxy S6, Lollipop, 10 July, 4:30pm mt

**Comment by nagapampa** [comment]
Connection refused for:
https://ccrjsfs.murfie.com/josh-sahunta-lights/01-supernova-feat-kayla-patrick-and-dexter-twardzik.m4a
https://ccrjsfs.murfie.com/josh-sahunta-lights/lights-mp3.mp3

**Comment by nagapampa** [comment]
Can you see if your work yesterday resolved this issue?

**Comment by jjg** [comment]
We had an outage of ccrjsfs yesterday but it's back at this point so playback should be restored.

I'm in the process of migrating all the tracks stored on ccrjsfs over to ccrapi2 which is significantly more robust and closely monitored.

**Comment by prestonaustin** [comment]
@jjg please update this ticket when you finish that and assign to me, thanks!

**Comment by jjg** [comment]
Migration complete but needs media pointers updated by @mbrakken before the new media will be referenced.

I'll send this your way @prestonaustin since I think I'm done, but feel free to send back if that's not right :)

**Comment by prestonaustin** [comment]
@mbrakken Can you update the media pointers and ping me on this ticket
after? If you can't do that right away, please assign yourself (I'm not
sure how via email).

**Comment by mbrakken** [comment]
It's on my list. I'll get to it a bit later. It's easy, but slow (unless I
come up with something clever to automate it).

**Comment by lahollen** [comment]
we believe this is closed by mms pointer updates

**Comment by acecarruthers** [comment]
When is a good time to test it out?

**Comment by prestonaustin** [comment]
@acecarruthers please hold off on tests until my next update, currently
expected later this afternoon after Marc is able to check in. We need to
ensure all work in progress is deployed and testable.
