### ISSUE TITLE
retrieve artist contact data

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#36]
Alex needs contact data for the artists on this list who submitted but were not accepted to CCR to send rejection letters. 
List of artists:
https://docs.google.com/spreadsheets/d/1yTDqOrVKAi32dP9a-EnKxDdocBFs1vbeobBUedawpf0/edit#gid=0

**Comment by prestonaustin** [comment]
Rather than pulling just the missing set, let's design this to pull emails for all artists, cuz why not?
- [ ] @mbrakken will give @nagapampa instructures (and/or insttructuions ;) about best way to pull that data. Please add/link them to this thread.

**Comment by nagapampa** [comment]
The spreadsheet has been updated with the contact information for each artist.
