### ISSUE TITLE
Text edits on FAQ page

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#41]
http://ccr-public.herokuapp.com/faq?anchor=accepted-music

- [x] Who is on the jury? Please change Lori Gawryluik’s title to “Artistic Director, Quarters Arts Society”
- [x] How much are the honorariums? Please change last sentence to “These royalties will be redistributed according to SOCAN and CSI’s policies.”

**Comment by nagapampa** [comment]
These changes will be deployed with the DELETE branch changes

**Comment by nagapampa** [comment]
This has been deployed
