### ISSUE TITLE
Install wildcard SSL

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#42]

**Comment by lahollen** [comment]
Blocked by Peter. We're inviting Peter to github and will assign this task to him.

**Comment by jjg** [comment]
Got the certificate this morning, will be installing and making associated DNS changes once @prestonaustin blesses them :)

**Comment by prestonaustin** [comment]
@jjg blessed be the plan.

**Comment by prestonaustin** [comment]
musicat and edmonton CNAME records for wax are in place as of 3 minutes ago.

**Comment by prestonaustin** [comment]
Done, works :)
