### ISSUE TITLE
Login box issues

### ISSUE THREAD

**Issue by lahollen** [therabble/ccr-app#43]
http://ccr-public.herokuapp.com/
- [x] Strange sizing of the login box on chrome and firefox. See https://docs.google.com/document/d/1_jd19GQLJ8DJl-IlILwWDxnYsVDgYfgF_V330D7CEcs/edit# for Alex's screenshot.
- [x] Remove up/down arrows in card number and PIN fields
- [x] Change “Library Card PIN” to “PIN”

**Comment by nagapampa** [comment]
Will be included in next deploy (of DELETE branch changes)

**Comment by nagapampa** [comment]
![login](https://cloud.githubusercontent.com/assets/2964839/8581180/bb709602-2584-11e5-906e-cfa0cd5f58b8.png)

**Comment by nagapampa** [comment]
This has been deployed.
