### ISSUE TITLE
AAC / ALAC need to be wrapped as M4A for downloads

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#51]
Everything else about this is in the murfie/mms repo.

**Comment by prestonaustin** [comment]
We think this bug will close without further work when @jjg closes https://github.com/murfie/mms/issues/25 - I'll update this ticket Thursday to give EPL visibility on status.

**Comment by prestonaustin** [comment]
@acecarruthers currently we have this fix for beta-done, but would like to consider moving it to production-ready and removing the option to download AAC & ALAC until it is done. Would that be acceptable? We have some issues with the heterogeneous sources that are new to CCR (because we didn't pull all the music from CD or other WAV source). It won't delay the work, and we think it's no big deal but it turned out not to be totally trivial either. It should be largely a semantic change to plan to get you launched today, and I'll provide an update soon.
Note: Both iPhones and Android should be able to do just fine with the MP3 option there.

A straight up yes or no is fine at this point.

**Comment by acecarruthers** [comment]
@prestonaustin yes - Go ahead and move it to production ready

**Comment by prestonaustin** [comment]
@jjg I believe your current work MMS/JSFS will close this ticket, please assign it back to me if that seems untrue.

**Comment by jjg** [comment]
I'll still need to define a `fmt` code for MMS to generate these, so I'll keep this open until that's done.

**Comment by jjg** [comment]
It's become clear that it's not possible (at least with an ffmpeg-based transcoder) to stream output in an MP4 container.  

To support this is going to require either a different transcoder, or an MMS mode that doesn't "pipeline" the transcoding process.  This doesn't rule out the appearance of a streaming mode, but it means that MMS will essentially have to buffer the transcoding output before delivering it to the client.  This is a deviation from how MMS handles other formats so I'm going to have to do some homework to see what it would take to re-work MMS to function this way for these requests.

Before doing that, I'm going to throw a little time at seeing if there is an alternative to ffmpeg-based solutions that can generate an mp4 stream in a pipelined fashion.  The container format has a provision to support streaming playback, so I don't think there's a hard technical barrier (at least not yet) so there may be a way to work around it.

**Comment by jjg** [comment]
After looking into pipelining options for mp4 it looks like buffering is going to be the way to do this.

**Comment by jjg** [comment]
I added what I'd consider "experimental" support for AAC in MP4 containers to MMS.  A build that supports this has been deployed in to production, the `fmt` specifier for this new format is `aac_mp4`.

I have tested the basic functionality using this build to generate .m4a audio files and it appears to work as it should.  A request for this format takes longer to start receiving data than previous formats because it has to buffer the output during the request, but it's not terrible (~9s from request to completed download using my ~4min test track).

I'm not sure how you'd like to move forward testing this, or exactly how it's used in the CCR application, but give it a look and let me know if you run into any trouble.  If it looks good, I'll add support for ALAC inside MP4 as well, but I want to hold-off until I'm sure things are working correctly.

**Comment by lahollen** [comment]
@nagapampa can you test this?

**Comment by prestonaustin** [comment]
For reference @jjg, this is used in the application on clickable download links for tracks, so each track carries a link to download it in mp3, aac, alac, or flac. In theory, streaming mode would avoid using anything but mp3, but in practice we might use the m4a aac for that as well on some apple browsers.

**Comment by nagapampa** [comment]
@prestonaustin I'm not quite sure how to test.  I am able to download and listen to mp3 and acc - not flac and alac.

**Comment by prestonaustin** [comment]
What URL are we calling for AAC?

**Comment by prestonaustin** [comment]
@nagapampa @jjg I still don't know if we have tested @jjg new fmt specifier for this new format, "aac_mp4" - Carie did you update the calling code before testing? If not, that certainly needs doing.

**Comment by mbrakken** [comment]
#96 should allow testing of this. I'm booting it up now to test.

**Comment by mbrakken** [comment]
And if test works, can be deployed.

**Comment by mbrakken** [comment]
Currently getting a 502 Bad Gateway on this, with the following url:
`https://mms.murfie.com/tc?src=https://ccrapi2.murfie.com/complete-submission/albums/f-and-m-at-sunset-we-sing/01-hands-in.wav&fmt=aac_m4a&auth=foo&meta={"tags":[{"key":"artist","value":"F&M"},{"key":"authors","value":"F&M"},{"key":"album","value":"At Sunset We Sing"},{"key":"title","value":"Hands In"}]}`

This url works (for mp3):
`https://mms.murfie.com/tc?src=https://ccrapi2.murfie.com/complete-submission/albums/f-and-m-at-sunset-we-sing/01-hands-in.wav&fmt=mp3&auth=foo&meta={"tags":[{"key":"artist","value":"F&M"},{"key":"authors","value":"F&M"},{"key":"album","value":"At Sunset We Sing"},{"key":"title","value":"Hands In"}]}`

**Comment by mbrakken** [comment]
pinging @jjg re: 502 Bad Gateway

**Comment by mbrakken** [comment]
Ahh. I see a problem. Updating.

**Comment by mbrakken** [comment]
Updated #96. I just downloaded a track in aac and it played in itunes.

**Comment by prestonaustin** [comment]
@mbrakken Let's wait for confirmation of @jjg's ALAC support, test both on an iPhone, and close this. (If not the right course of action, please define what is.)

**Comment by mbrakken** [comment]
Sounds right to me @prestonaustin

**Comment by jjg** [comment]
Experimental ALAC support deployed.

**Comment by mbrakken** [comment]
sweet. I'll switch over and test

**Comment by mbrakken** [comment]
OK. xhr request to this url (alac): 
`https://mms.murfie.com/tc?src=https%3A%2F%2Fccrapi2.murfie.com%2Fcomplete-submission%2Falbums%2Ff-and-m-at-sunset-we-sing%2F03-kukushka.wav&fmt=alac_mp4&auth=foo&meta=%7B%22tags%22%3A%5B%7B%22key%22%3A%22artist%22%2C%22value%22%3A%22F%26M%22%7D%2C%7B%22key%22%3A%22authors%22%2C%22value%22%3A%22F%26M%22%7D%2C%7B%22key%22%3A%22album%22%2C%22value%22%3A%22At%20Sunset%20We%20Sing%22%7D%2C%7B%22key%22%3A%22title%22%2C%22value%22%3A%22Kukushka%22%7D%5D%7D`

It starts off happy: `loadstart` triggers right away, a short pause and then `progress` events start streaming in until it hangs at 
```javascript
progress { target: XMLHttpRequest, isTrusted: true, lengthComputable: true, loaded: 41064613, total: 72828496, currentTarget: XMLHttpRequest, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1438034016715259 }
```
Then it stops for a while until an `error` event:
```javascript
error { target: XMLHttpRequest, isTrusted: true, lengthComputable: false, loaded: 41064613, total: 0, currentTarget: XMLHttpRequest, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1438034134424108 }
```
and closes with a `loadend`:
```javascript
loadend { target: XMLHttpRequest, isTrusted: true, lengthComputable: false, loaded: 41064613, total: 0, currentTarget: XMLHttpRequest, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1438034134430847 }
```
I notice that between the last `progress` event and the `error`, `total` gets set to 0 (from 72828496 in this case).

There's no `statusText`; I'm setting `responseType:"blob"` on the request. I'm not really sure if there's more useful information in here @jjg, but I'm happy to test out and provide whatever I can.

**Comment by jjg** [comment]
I just deployed a change that returns an accurate `Content-Length` for "buffered" MMS output formats (notably `aac_mp4` and `alac_mp4`).

I have tested both and they appear to be working as expected now, so I think that will resolve this issue @mbrakken but please let me know if not, thanks.

**Comment by mbrakken** [comment]
seems to all be working. closing.
