### ISSUE TITLE
spec what's needed in terms of MMS compression/size/etc

### ISSUE THREAD

**Issue by prestonaustin** [therabble/ccr-app#53]
@jjg I'll do this with @mbrakken and @nagapampa post beta, then pass to you

**Comment by prestonaustin** [comment]
@jjg I'm not going to constrain how this works at all I've decided. But we want, in order, to have client call be able to request the image with a specific format, crop (portion of its original source dimensions to return), size, and level of compression. If the only supported output were jpg at first, that's fine, as that's what this is 99% for right now.

**Comment by jjg** [comment]
Is jpg required or is png (already supported) acceptable?

**Comment by prestonaustin** [comment]
If implementation supports jpg compression in the PNG container, it's fine.
(Compression is an issue, currently some images are cray cray hugemongous :)

**Comment by jjg** [comment]
I left this issue open for tracking purposes but all further work will be tracked under:

 https://github.com/murfie/mms/issues/33

Feel free to close this Issue if appropriate @prestonaustin
