### ISSUE TITLE
handle download feedback when evt.lengthComputable === false

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#55]
Currently, mms doesn't reliably give back computable lengths during download. We should have a fallback state on the download indicator, akin to the "processing" state on the upload indicator in the ccr app.

**Comment by prestonaustin** [comment]
@mbrakken is this deprecated by @jjg's current work.

**Comment by mbrakken** [comment]
I don't know yet, although it's presumably still good to have this in as a fallback for slow connections or something.

**Comment by prestonaustin** [comment]
@mbrakken I think this ticket is deprecated? If so please just close it.

**Comment by mbrakken** [comment]
I guess I'll close, but I think there are still times where we want to show indeterminate progress. I'll wait for an issue to arise, though, particularly since there's conversation afoot to update how we present download progress.
