### ISSUE TITLE
Individual poster images uploading slowly

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#58]
We received this feedback from two beta testers this morning. This was a general comment and not a concern about a specific poster. 

(beta tester 1, Chome on Windows 7, 9 July, 5:05pm mt
beta tester 2, Firefox on Mac OS X, 9 July, 8:41pm mt)

**Comment by acecarruthers** [comment]
@prestonaustin when I add a new issue is it best that I mention you in a comment like this? Or should I assign it to you or @lahollen so that you can review my tags and assign the issue to the right people?

**Comment by prestonaustin** [comment]
@acecarruthers you don't need to do anything actually. I watch the repo so
I see all new issues (like that eye in the Lord of The Rings only less
creepy). A good example of a well formed ticket are these from John and me.
Note the stuff in parens - that helps a lot. Ideally we know which tester,
browser, OS, and anything special like using it on a mobile network with
each report, along with estimated time and day)

If you wish, I'll create a form for folks to report with, but I like to
avoid that as it can tend to decrease reporting pretty dramatically.

Examples here:

https://github.com/therabble/ccr-app/issues/57
https://github.com/therabble/ccr-app/issues/56

It's also OK to email those details to Lisa and I to create tickets, when
you don't have time or access for github, although starting there is much
better unless you can't.

**Comment by acecarruthers** [comment]
@prestonaustin ok great. Thanks for the suggestion. I'll just add issues directly to GitHub with as much detail as I can.

**Comment by prestonaustin** [comment]
Also - keep in mind that the whole world can see us in here should they
happen to look, as this is an open dev repo, so don't share contact info
here.

**Comment by lahollen** [comment]
we think this will be closed by other issues. report new problems in new issues.
