### ISSUE TITLE
Content on "Rend" artist page not showing up

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#59]
I published this band yesterday morning. The album page has no problems at all. 

(Alex, Firefox, Windows 7, http://wax.capitalcityrecords.ca/artists/rend 10 July, 10:17am mt)

**Comment by mbrakken** [comment]
Their submitted youtube url was http://www.youtube.com/rendmusic, which is different from the others and the parsing code didn't know how to deal with to load in the youtube playlist. That url redirects to https://www.youtube.com/user/RENDMUSIC, which should parse fine, so I'm going to change the url.

**Comment by mbrakken** [comment]
http://wax.capitalcityrecords.ca/artists/rend loads.
