### ISSUE TITLE
Text edit to FAQ page

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#60]
Under "How can I download music?" please replace "[specific instructions on how to download music]" with "Log in with your library card and PIN by clicking the Login button in the top right corner. Then hover over the track you want to download. Click the download button that appears next to the track play button. Choose the format you want to download. Enjoy!" 

http://wax.capitalcityrecords.ca/faq

**Comment by nagapampa** [comment]
Checked into master for next deployment
