### ISSUE TITLE
Player doesn't update immediately when switching between albums

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#61]
When you switch from one album to another on the player, the new track names appear, but the album art, artist name and album name do not change. Once song 1 has played through and song 2 begins, all of the correct data appears in the player for song 1. 

(beta tester 1, Chrome, Windows 7, 9 July, 5:06pm mt
Alex, Firefox, Windows 7, 10 July, 2:17pm mt brightly annotated screen grab below from http://wax.capitalcityrecords.ca/albums/mark-davis-eliminate-the-toxins
![playerupdate bug](https://cloud.githubusercontent.com/assets/7355887/8628240/80dd4d88-270e-11e5-9748-34bb8ebc7dcd.jpg)
)

**Comment by mbrakken** [comment]
I may have been a bit vigorous in unbinding data on the player. I thought I
was just unbinding it in one way (eg. the interface won't update the
model), but I may have unbound it both ways. I'd start by removing some of
the `unbound` statements in the template and go from there.

**Comment by acecarruthers** [comment]
Today this bug manifested itself a little differently. After switching between albums, the song that was playing would continue to show the incorrect artist name, album art and album cover, but, the songs to the left and right of the playing song would have all the correct information.

**Comment by prestonaustin** [comment]
@mbrakken please update this ticket

**Comment by mbrakken** [comment]
will be closed by #76.

**Comment by mbrakken** [comment]
reassigned for test/merge/deploy

**Comment by acecarruthers** [comment]
Album name doesn't change when you switch albums. See screen shot. 
Consistently showed up this way for multiple albums on:
windows 7, firefox & chrome, 
iPad, iOS 8.3, Safari 8 
20 July 5:30pm mt

![soooplaybar_err](https://cloud.githubusercontent.com/assets/7355887/8790009/eadddd52-2f05-11e5-8f18-7e40af6eff5e.jpg)

**Comment by nagapampa** [comment]
Unbound this field.  Will be in next deploy.
