### ISSUE TITLE
Few seconds of songs repeating at the end of tracks

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#62]
This is a bug I noted earlier and I believe it is tied to #28.

(beta tester 2, Firefox, Windows 7, noticed between tracks 1/2 of http://wax.capitalcityrecords.ca/albums/lauren-busheikin-we-love, and between tracks 1/2 and 2/3 of http://wax.capitalcityrecords.ca/albums/jey-witten-the-wide-eyed, 9 July, 5:15pm mt)

**Comment by prestonaustin** [comment]
Review after Jason fixes to MMS and JSFS

**Comment by jjg** [comment]
MMS and JSFS changes made, need to re-test after @mbrakken updates the track pointers.

**Comment by jjg** [comment]
All tracks stored on ccrapi2 should now be available in wave format.  Original versions have been preserved at their original locations, and new paths are identical but for a ".wav" extension.

**Comment by lahollen** [comment]
@jjg is this resolved?

**Comment by jjg** [comment]
Need to verify with @mbrakken that the pointers are updated and then this can be re-tested.

**Comment by lahollen** [comment]
retest after #8 #51 #83 close and deploy

**Comment by mbrakken** [comment]
All pointers, with the exception of three tracks from Look Away, have been updated. MMS is in use on production as well.

**Comment by prestonaustin** [comment]
@mbrakken @jjg Anything blocking this?

**Comment by mbrakken** [comment]
I believe we should now test it all. I've provided more info to @jjg about the remaining 3 tracks, as well as 42 other tracks in wav that do not appear to have been processed in the new context (ie they don't have all the additional media headers). So, barring those I think we can just test away.

**Comment by mbrakken** [comment]
test away.

**Comment by prestonaustin** [comment]
Not seeing it, closing.
@acecarruthers you should definitely get this retested as well, and reopen with details if observed on any tracks.
