### ISSUE TITLE
Google Analytics set up and functioning

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#63]
EPL has a Google Analytics account. I'll set up a special certificate for capitalcityrecords.ca and share the code.

**Comment by prestonaustin** [comment]
@acecarruthers please assign to Carie after you have the code.

**Comment by mbrakken** [comment]
Per meeting today, I'm assigning this to @jdlien since it means poking into the code base but pretty much stands alone.

There's an example on [ember guides] (http://guides.emberjs.com/v1.13.0/cookbook/helpers_and_components/adding_google_analytics_tracking/), although I don't know if it's current. It seems like a good place to start.

NB: Initially I was going to suggest doing this as a service, but since it's something that happens on each transition, the router seems like the place for it (the above link has it in the router). If additional ga reporting is expected for user actions such as downloads, I'd recommend either constructing a separate service or else add to the logging service at [services/logger.js] (https://github.com/therabble/ccr-app/blob/master/app/services/logger.js).

**Comment by mbrakken** [comment]
Pinging @nagapampa so she gets updates to this thread.

**Comment by acecarruthers** [comment]
Tracking code for @jdlien 

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65362402-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by nagapampa** [comment]
@acecarruthers Any chance I can get your GA credentials so I can test if the code is working?  It takes up to 24 hours to start showing any data so I won't need this for a day or so for testing completely.

**Comment by nagapampa** [comment]
@acecarruthers I also need the GA ID as soon as you can get that to me.

**Comment by nagapampa** [comment]
Thanks @acecarruthers 

Code has been deployed.  Let the tracking begin.

**Comment by acecarruthers** [comment]
@nagapampa I am new to Google Analytics and discovered this afternoon that some of the things I want to track will require additional tracking information added to the album pages. I haven't quite figured out what specifically I need (if you have experience with GA maybe you could help me out) so I may ask for more help on this tomorrow or on Tuesday. 

I'm going to try and track song streams and downloads as events.  I want to be able to track:
- Number of daily streams and downloads
- Number of new and returning visitors who perform actions on the site daily (stream, download,)
- Number of unique visitors who perform actions on the site daily (stream, download)

I don't think this is urgent because I believe we'll be tracking similar info for CSI/SOCAN. It won't block the launch. I'd be interested in possibly talking about how we could avoid GA for this tracking altogether, but that might be a conversation for down the road.

**Comment by acecarruthers** [comment]
According to this documentation: https://developers.google.com/analytics/devguides/collection/analyticsjs/events, in order to track when a song is streamed or downloaded, we need to set up 2 unique trackers for each song. For https://wax.capitalcityrecords.ca/albums/columbus-commonwealth that would be something like: 

``
ga('send', 'event', 'music', 'stream', 'columbus-aolathome');
``
``
ga('send', 'event', 'music', 'download', 'columbus-aolathome');
``

Setting up two trackers for each song seems very time consuming and we don't actually need data about which specific tracks are streamed or downloaded. We just want to know the total number of streams and downloads per day associated with different user types. @nagapampa is there a way that we can tie the tracking code to the playbar so that each time a new song starts playing an event is registered? Are you able to suggest a good way of moving forward with this?

**Comment by nagapampa** [comment]
Will be in the next deploy.

Also, the page tracking is working!  Log in and check out the stats (mostly under Behavior -> Site Content -> All Pages)

The track events should show up later today or at least by tomorrow.
