### ISSUE TITLE
Mobile functionality issues

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#64]
- [ ] download process on tablet is not obvious. On Safari and Chrome you have to hold your finger down on the track you want until it is highlighted. Then dismiss the copy button and then the button appears. Could this be simpler? 
- [ ] download button appears over the play button on phone. Only the play button responds to tapping. See screenshot below. 

Alex iPad iOS, Safari 8.3, 10 July 4:50pm mt & Samsung Galaxy S6, Lollipop, Chrome, July 4:50pm mt  
![screenshot_2015-07-10-16-26-21](https://cloud.githubusercontent.com/assets/7355887/8630659/c923bb9c-2725-11e5-8499-4b6d54df43da.png)

**Comment by prestonaustin** [comment]
Let's split the banner image squish into another ticket. We don't need new
ones we can automate it.

The other two need a different style for touchscreens, it's the onhover
stuff that is making it awkward. I think the control for download of each
track should simply show at all times.

(I'll make these changes and assign the tickets later, this is just in case
someone gets to these before I do)

**Comment by mbrakken** [comment]
Yup. A touch alternative is in plan. I need to resolve this for murfie, so
ill share info when i have that.

**Comment by acecarruthers** [comment]
I moved the image squish into #71 with some other non-blocking mobile bugs.

**Comment by acecarruthers** [comment]
related feedback: "At first the download button was there when I was streaming music. It accidentally clicked on the download. I decided I would come back to that function as I was focusing on streaming. But then the download icon was not even there (did not load?) I waited and clicked on other artists. Could not download." 

tester, Safari, iOS, 15 July, 9:10 pm MT

**Comment by prestonaustin** [comment]
@mbrakken please update this ticket, we need an MVP defined here or reassign it to me (but then you have to implement my solution for Murfie stuff too ;)

**Comment by mbrakken** [comment]
style / positioning is just css. only needs doing. to handle touch screens, I think something like
```javascript
if ("ontouchstart" in window || navigator.msMaxTouchPoints) { document.body.classList.add('with-touch') }
```
within the app boot process (application route?) and then update various things that relate to hover state to always be visible if `body.classList.contains('with-touch')`. This would include some css and some updates in components during their `init()` hook.

**Comment by mbrakken** [comment]
fwiw, mobile in general needs a thorough overview (login, menu, etc). I just didn't have time for that.

**Comment by mbrakken** [comment]
also, I have different versions of those mobile menu icons. those were some I hacked together from resources given to me in the wrong format.

**Comment by mbrakken** [comment]
I just updated the touch detection snippet.

**Comment by prestonaustin** [comment]
@mbrakken you said "I have different versions of those mobile menu icons."
- what needs to happen with those, where are they, who should do it?

**Comment by mbrakken** [comment]
![mobile-icons](https://cloud.githubusercontent.com/assets/1530955/8735745/bd44013a-2bd8-11e5-808e-c16c77fd2ed8.png)

**Comment by mbrakken** [comment]
this is the png sheet I now have, with transparent background. I was planning to colorize and duplicate these to make one sheet with blue and white versions. The initial set I had as jpg on white, so frayed edges in currently deployed version are the result of my non-photopshopy skills.

**Comment by mbrakken** [comment]
I'm not sure if I should still be assigned this or not. I think @nagapampa could handle this from here, but that there's a chance it'll come back to me anyways. I'm unassigning myself for now, to show it as "available to be picked up by someone".

**Comment by prestonaustin** [comment]
@nagapampa I believe you should be in a position to finish this one off, once we get the art from Daniella to do so.

**Comment by lahollen** [comment]
@nagapampa link to art: https://www.dropbox.com/s/abwyrzevqkyi631/mobile-icons-v2.png?dl=0

**Comment by nagapampa** [comment]
@prestonaustin @lahollen 
Did you want me to just always show the download icon?  (instead of the mouse over effect)
Also, what is the new art linked here?  Are the icons changing to be black now?  This sprite doesn't have a rollover color either.

**Comment by prestonaustin** [comment]
> Did you want me to just always show the download icon? (instead of the
mouse over effect)

Yes let's try that.

> Also, what is the new art linked here? Are the icons changing to be black
now? This sprite doesn't have a rollover color either.

Hmmm, I didn't spec this so I'm not sure. Let's open a new ticket for the
nav art update and set it aside from this milestone. This can be improved
at any point.

**Comment by mbrakken** [comment]
RE: colors, I had planned to take the base sprite and turn it into a single sheet with 2 versions of each, white and the blue in use. I can mux with it.

**Comment by mbrakken** [comment]
![mobile-icons-v3](https://cloud.githubusercontent.com/assets/1530955/8914830/0b331930-3467-11e5-94d4-b4f35ab5e3e4.png)

**Comment by mbrakken** [comment]
There are white versions in that image :)

**Comment by prestonaustin** [comment]
@nagapampa @mbrakken I'm unclear what still needs doing here. If anything does, let's create new independent tickets for anything on download touch UX, or mobile menu, that remains end of today and close this.

**Comment by prestonaustin** [comment]
@nagapampa can you close this out? If not, I need to know what blocks it.

**Comment by nagapampa** [comment]
merged PR.  changed duration to show up only in desktop.  the download button will always show now.  rest of changes can be put into new redesign ticket.
