### ISSUE TITLE
First track of multiple albums not playing

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#65]
Not every album has been tested, but so far this was identified as a problem for
Passburg http://wax.capitalcityrecords.ca/albums/passburg-mountains
Electricity for Everybody! http://wax.capitalcityrecords.ca/albums/electricity-for-everybody-local-technique
Unwed Mothers http://wax.capitalcityrecords.ca/albums/unwed-mothers-unwed-mothers  

(Alex, Firefox, Windows 7, July 13, 9:20am mt
beta tester, Chrome, Windows 7, July 13, 9:10am mt)

**Comment by prestonaustin** [comment]
Clarifications needed (unassigned - @jjg just FYI)
- [ ] determine if this is all the time, all clients
- [ ] check browser network activity to determine if if a media object is
being returned (corrupt result vs fail with no result)

**Comment by jjg** [comment]
Just so I have a crystal-clear picture of this, is it always the first track, or the first track played?

**Comment by prestonaustin** [comment]
@acecarruthers do you know/can you find answer for @jjg question above?

**Comment by acecarruthers** [comment]
@jjg it has been the first track. With Passburg it looks like it is track no. 1 and track no. 2. The order you play them in doesn't seem to matter.

**Comment by prestonaustin** [comment]
@jjg after you normalize the JSFS representations of all tracks to WAV, and finish the work associated with playback duration metadata, can you test these and close the ticket or assign it back to me.

**Comment by jjg** [comment]
Waiting on @mbrakken's media pointer updates.

**Comment by jjg** [comment]
Currently blocked by https://github.com/therabble/ccr-app/issues/78, reassigning but if still an issue after 78 is closed, please send it back my way :)

**Comment by mbrakken** [comment]
Pointers have been updated. FWIW, I had noticed this intermittently, and was wondering if it was related to formats or legacy storage issues. I just tested the above listed 3 albums, and they all played as expected. Firefox, 39.0, OSX 10.9.5

**Comment by mbrakken** [comment]
I'm going to close this @prestonaustin, since tracks seem to play fine for me. Please reopen @acecarruthers if this issue resurfaces.
