### ISSUE TITLE
Indication that download is processing

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#67]
The time in between choosing a download format and seeing the browser's indication that the file has downloaded was long enough that one tester became confused about whether she was doing it right. Please add a visual indication that the file is downloading.  

She was testing on http://wax.capitalcityrecords.ca/albums/mad-bomber-society-butchers-stompers-and-cheats, but I've tried a few times and had similar results on other pages

tester, Chrome, Windows 7, 13 July, 10am mt
Alex, Firefox, Windows 7, 13 July, noon mt

**Comment by prestonaustin** [comment]
- [ ] provide UX feedback at or before query initiation for download: "downloading..." in the track bar and clear that feedback at download completion.

**Comment by mbrakken** [comment]
There should in fact already be a progress indicator (for download to browser). #55 relates to that.

@acecarruthers are you rdownloadig during track playback? I was in a big hurry to get the download stuff done so it's likely that the indicator is hidden behind the playbar when the playbar is visible.

**Comment by acecarruthers** [comment]
hey yeah, I _was_ downloading during track playback and so was the other tester. I tried downloading without the playback and I saw the indicator. It looks good. Could it float above the playbar when the playbar is visible?

**Comment by acecarruthers** [comment]
The download indicator does not appear on my iPad screen. 
iOS 8.3, Safari 8, 20 July, 4:50pm MT.

**Comment by jjg** [comment]
Can iOS devices download media files?

**Comment by acecarruthers** [comment]
I have not successfully downloaded anything on my iPad yet.

**Comment by lahollen** [comment]
@nagapampa can you give an update on this ticket?

**Comment by nagapampa** [comment]
Changed z-index of player to be less than the download progress bar.  Now the bar will always be on top.
