### ISSUE TITLE
Dropped Vimeo logos appear on artist pages

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#69]
See example below. The images appear on different artist pages in different orders and often disappear if the page is refreshed. @mbrakken looked at this a month ago and we thought we had resolved it, but I've received reports of it continuing to happen from testers. 

(tester, Chrome, Windows 7, http://ccr-public.herokuapp.com/artists/doug-hoyer, http://ccr-public.herokuapp.com/artists/bombproof-the-horses, 9 July, 11:41AM mt
tester, Chrome, Windows 7, http://wax.capitalcityrecords.ca/artists/souljah-fyah, 13 July, 10am mt
Alex, Firefox, Windows 7, http://wax.capitalcityrecords.ca/artists/souljah-fyah, 13 July, 1:25pm mt)

![weird image](https://cloud.githubusercontent.com/assets/7355887/8658565/dac41d4a-2961-11e5-994e-ba0a5da57007.png)

**Comment by prestonaustin** [comment]
@mbrakken You have familiarity with this issue, what is going on here in your opinion?
(answer soon please, even if you don't have a lot to say)

**Comment by mbrakken** [comment]
In almost all (every?) case, this is a data issue. All logos are in one image, and they're positioned based on class names parsed from the url (eg `class="facebook"` if a facebook url). There's no default logo (or image positioning) if we can't parse a matching class.

I don't currently see this occurring in any of the examples above, so I can't really debug it. The most helpful thing would be to report what (if and) urls those link to when we see them.

**Comment by prestonaustin** [comment]
@mbrakken This seems clever, but fragile. Can we talk it through on Tuesday
in person and find a way to be more clever about it? Otherwise it seems
like adding a new kind of URL requires a few to several updates to code and
assets.

**Comment by mbrakken** [comment]
Yeah. This was the version based on what existed, both in terms of data structure and actual data. A generic fallback image probably makes sense, at least for the interim. We'd want to include that (both color versions) on the same sprite sheet, ideally in a way that doesn't displace positioning of anything already on it (eg appended to the right of the existing images).

**Comment by prestonaustin** [comment]
*barfs*

**Comment by mbrakken** [comment]
oh, it's not that bad :)

**Comment by acecarruthers** [comment]
@mbrakken encountered another one of these today. The URL links to the artist website, which reminded me that the earlier examples from the tester were also linking to the artists' websites.  

http://wax.capitalcityrecords.ca/artists/jesse-and-the-dandelions 
artist website: http://jesseandthedandelions.com/

**Comment by lahollen** [comment]
@mbrakken do you have an update from daniella?

**Comment by lahollen** [comment]
@nagapampa links to art: 
https://www.dropbox.com/s/rlqoh518le7k0te/social-media-icon-v2.png?dl=0
https://www.dropbox.com/s/zhfu28b42pqlsqo/social-media-icon-grey-v2.png?dl=0

**Comment by nagapampa** [comment]
@acecarruthers This is happening because of incorrect data input.  I went to the review and publish for:
http://submissions.capitalcityrecords.ca/review-and-publish/submissions/jesse-and-the-dandelions-a-mutual-understanding

Look at the social media input.  There WAS an extra comma here at the end (http://www.facebook.com/jesseandthedandelions, https://twitter.com/jessedandelion,).  When this happens, the code assumes another value.  Since nothing is there, the class for the social media icon is NULL, hence you see the 'off' icon.  I removed the comma and now everything looks good.
http://www.facebook.com/jesseandthedandelions, https://twitter.com/jessedandelion,

**Comment by acecarruthers** [comment]
I just encountered another one of these on http://submissions.capitalcityrecords.ca/review-and-publish/submissions/choir-and-marching-band-life-found-on-superhot-body-only-one-light-year-away 

Beside the facebook logo was the vimeo logo linking to the artist website. 
![droplogo_choir_7272015](https://cloud.githubusercontent.com/assets/7355887/8914060/30862bc6-345a-11e5-859f-4e08689819ea.jpg)


On the admin side there was no extra comma. I put the cursor at the end of the link to facebook and pressed delete a bunch of times and then published it again. When I refreshed the page, the vimeo logo disappeared, but I am not certain it is because I deleted any extra spaces. Previous times when I have encountered this weird logo, just refreshing the page has made them go away.

**Comment by prestonaustin** [comment]
@mbrakken can you confirm that @nagapampa has the art needed to wrestle this issue to the ground? If we cannot fix the current sprite and substring-mapping approach to this today, I believe we should scrap that approach and this design temporarily, replace it with something less fragile so we don't risk stuff being graphically broken and do have the links available, and revisit implementation of this design after launch.

**Comment by mbrakken** [comment]
Well, there are likely 2 issues in play. I still think the strange appearance of extra anchor tags is an artifact of either data (although that should be resolved by now), or things getting muxed due to memory issues/leak, but these sprites will give us a fallback option.

![social-media-icon-grey-v3](https://cloud.githubusercontent.com/assets/1530955/8918545/46f510ba-347e-11e5-89b1-64e61e5c64f1.png)
![social-media-icon-v3](https://cloud.githubusercontent.com/assets/1530955/8918546/46fb4354-347e-11e5-98d8-c65ce42387fd.png)

**Comment by nagapampa** [comment]
I'm all for the webfont icons!

I just tested and made sure there weren't any spaces/commas in the submission.  It looks good in my browser now (Chrome)

**Comment by prestonaustin** [comment]
@nagapampa can you close this out now with the new sprite sheet?

**Comment by nagapampa** [comment]
I believe this was a data issue - not sprites.

**Comment by mbrakken** [comment]
The sprites should be updated and the globe image on the sprite should be positioned as a fallback (no matching class), so the styles for `.sm-link` link should be updated with a default `background-position` (in `_artists.scss`).

Then at least things won't look janky.

**Comment by acecarruthers** [comment]
@nagapampa I just caught another one of these on the jesse and the dandelions page. It doesn't seem as though removing the comma permanently resolved this. 
(Windows 7, Firefox 39, 28 July, Noon, https://wax.capitalcityrecords.ca/artists/jesse-and-the-dandelions)

**Comment by prestonaustin** [comment]
"hate" is not too strong a word for how I feel about this github issue :/
@mbrakken @nagapampa let's talk about this at 1:30 and decide our path,
then update this ticket with that decision.

**Comment by mbrakken** [comment]
closed by #99
