### ISSUE TITLE
Mobile login sizing

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#70]
First attempt at logging in on iPhone 5S resulted in strange sizing and floating navigation bar. See below. The cursor was flashing where the PIN box should have been. Even though it wasn't possible to see the PIN box or the submit button, it was possible to successfully login from this screen. 

(tester, Chrome, iOS, 13 July, 10:30am mt)

![img_0436](https://cloud.githubusercontent.com/assets/7355887/8658876/d300bdf0-2963-11e5-919a-1065bb71399a.PNG)

**Comment by acecarruthers** [comment]
Similar feedback received yesterday: "the pop up window to put my card info into kept getting obscured my the music play bar. It seems all the displays were not fitting in my screen." 

(tester, iPhone, iOS, Safari, 15 July, 9:10pm MT)

**Comment by prestonaustin** [comment]
@nagapampa Let's create simplified CSS that makes this use the entire screen at narrow widths rather than rendering a modal in context of the page content. After implementation we'll look at any further needed styling.

**Comment by nagapampa** [comment]
Deployed.  I tested on my Android and this wasn't happening anymore.  @acecarruthers can you test on your iPhone as well?

**Comment by acecarruthers** [comment]
I wasn't able to test it on the original phone that noted the problem (wasn't mine), but it looks and works great on my colleague's iPhone 6.

**Comment by prestonaustin** [comment]
Let's close this then, unless we hear bad things from the world about it :)
