### ISSUE TITLE
Mobile Usability Issues

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#71]
- [x] banner images on tablet and phone do not scale down in size and end up looking squished. 
- [x] "More" button in phone navigation didn't do anything and tester was unable to logout from her phone. 
- [ ] player buttons too small and difficult to use
- [x] EPL logo/link is covered up by the mobile menu. 

tester, Chrome, iOS, iPhone 5S, 13 July, 10:50am mt

**Comment by prestonaustin** [comment]
- [ ] scale home page banner images on tablet and phone to design width
- [ ] Fix "More" button to show additional hidden copy
- [ ] Test logout from phone
- [ ] Move EPL logo/link above the mobile menu

**Comment by acecarruthers** [comment]
Final beta tester noted that they couldn't access "My Collection" from the mobile site. I figure My Collection will be revealed along with the other hidden copy behind More, but I thought it was worth saying explicitly. 

(tester, iPhone, iOS, Safari, 16 July, 1:13 pm MT)

**Comment by nagapampa** [comment]
Should we hide the banner completely on mobile?

**Comment by nagapampa** [comment]
@acecarruthers Would you like to hide the banner completely on mobile?  Or I can try making the text smaller...  Scaling the images will make the banner really small and make the text hard to read.

**Comment by acecarruthers** [comment]
@nagapampa is it possible to hide the banner on phone screens and scale it so it is a bit smaller on tablet screens? Or have you tested it on a tablet-sized screen and see that it is too small?

**Comment by nagapampa** [comment]
@prestonaustin 
Can you clarify this: Move EPL logo/link above the mobile menu

**Comment by prestonaustin** [comment]
I _think_ in the menu at the bottom, on phones, overlaps the bottom logo.
So, I believe we need to add some buffer at the bottom of the page so the
logo comes up over the menu. May need clarification from @acecarruthers if
that is not correct. This may only happen on very narrow devices.

**Comment by nagapampa** [comment]
@acecarruthers We could add the logo to the bottom, however this would eat up space on a mobile device.  I could try adding the footer logo if the text was removed and it was just the main logo part (if that makes sense), and adding the logo to the right of the More... button.  Thoughts?

**Comment by prestonaustin** [comment]
I like that option as well, FWIW.

**Comment by acecarruthers** [comment]
Here's a screenshot of the site on an iPhone 6 (it also looks like this on an iPhone 5). I think @prestonaustin's first thought was right that the logo should come up over the menu.  My phone has a wider screen and this is not an issue. 

(I also like the idea of just using the coloured bar part of the EPL logo, but our Marketing department is pretty particular about using the text and coloured bars together.)

![iphone6logo](https://cloud.githubusercontent.com/assets/7355887/8860060/6a00689a-313e-11e5-8d59-85bb81d18c3e.jpg)

**Comment by nagapampa** [comment]
![footer logo](https://cloud.githubusercontent.com/assets/2964839/8860714/318435e8-314b-11e5-9148-6747d3d3c48e.png)


@acecarruthers This is a screenshot from my Android Samsung S5.  Is this right?  If so, I'll see if I can add more padding from the bottom so it shows up for you.

**Comment by prestonaustin** [comment]
Could we crop just the "EDMONTON PUBLIC LIBRARY" text part off the left of
just the bottom logo, to avoid the overlap that is stacking the logo below
the "ABOUT  FAQ" text links on narrow widths?

That treatment is quite wide for flexibility on mobile, this will look
better on, and take less vertical space between content and bottom nav on,
narrow mobile screens.

**Comment by nagapampa** [comment]
@acecarruthers Can you test all the changes requested in this ticket except for: player buttons too small and difficult to use (can you tell me what you'd like to see for this - a bigger button/row/etc?)

I tested using Chrome's views for mobile including the iPhone and it looked good, but it's not the real thing.  Thanks.

**Comment by acecarruthers** [comment]
The more button was working great. The banner was gone and it looked good. The EPL logo resizing looks extra good on my Samsung now, but is still very hard to access on the iPhone. With the resizing, the About and FAQ links are also hard to access. It might have to do with the little Safari navigation bar at the bottom maybe? Here's the new screenshot: 

![iphone6new](https://cloud.githubusercontent.com/assets/7355887/8864175/3832009e-315c-11e5-84ee-6b817eec0950.jpg)

Re: playbar buttons. The feedback I've received is that people would like bigger buttons. It is difficult to press the buttons with precision right now because they are small and very close together. Maybe double the size?

**Comment by nagapampa** [comment]
@acecarruthers Can you test on your iPhone the logo at the bottom again please?  I added more margin to the bottom of the footer.

**Comment by nagapampa** [comment]
@prestonaustin Can we create a new ticket to tweek the album player in mobile?  If the play button gets bigger, the row needs to be bigger as well.

**Comment by prestonaustin** [comment]
Yes, I'll close this ticket tomorrow and open a new one for that player
design work. I need to find a smaller phone and get a feel for the problem
too.
