### ISSUE TITLE
Design modifications

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#72]
I spoke with EPL's head of design and production and he gave me some good feedback on the site. 
- [x] Move the CCR logo in the top left corner down so the bottom of the logo is on a level with the bottom of the search bar. 

- [x] Put some padding around the text on top of the banners so that the text isn't crowded at the top. I thought the spacing of the banner text on the homepage mock ups we received from Daniella looked really good. 

- [x] Please change the text on the poster banner to "Edmonton Concert Posters"

- [x] Please change text on album banner to say "Stream and download great tracks by Edmonton musicians" (no period)

- [x] We are working on redesigning the first banner (currently has black background and colourful buttons) to fit the aesthetic a little better. I will upload it here as soon as it is done so the new one can replace the current one. 

- [x] The text on the album banner and the poster banner are hard to read. We have mocked up two possible solutions to this - attached below. One with shadows behind the text and one with magenta bars behind the text. I'm partial to the magenta bars. Since the text is added on top of the images, we would need either the shadows or the magenta added in with CSS. Are either of these possible?

Magenta:

![ccr_banner_magentatext](https://cloud.githubusercontent.com/assets/7355887/8681257/b0a3acac-2a23-11e5-8dbb-5f92ea9e0029.png)

Shadows:

![ccr_sample_v2](https://cloud.githubusercontent.com/assets/7355887/8681282/cd300410-2a23-11e5-9546-942d75a43b91.jpg)

**Comment by prestonaustin** [comment]
Let's try magenta bars CSS first here, as it is Alex's pref (and imo CSS
more certain to always work with various art)

**Comment by prestonaustin** [comment]
Assigning to @acecarruthers until banner uploaded, please assign back to Carie when you get it in here :)

**Comment by acecarruthers** [comment]
![ccr_launch2_artbox_980x596_1_v6](https://cloud.githubusercontent.com/assets/7355887/8737352/499adaa0-2bde-11e5-8bd6-9ac179cf59c5.png)

**Comment by prestonaustin** [comment]
Ooooh...pretty :)

**Comment by nagapampa** [comment]
PR created and merged into master
