### ISSUE TITLE
mobile user unable to log in using otherwise functional card

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#73]
Survey feedback: "It would not accept my card number. I know my information is correct as I use the EPL app on my phone and often sign in."

tester, Safari, iOS, 15 July, 9:10 pm MT

**Comment by acecarruthers** [comment]
I just tested with my card number and had the same problem. 

Samsung Galaxy S6, Lollipop, Chrome, 16 July 10:04am mt

**Comment by prestonaustin** [comment]
@acecarruthers can we get the card numbers to test with or do all cards now fail?

**Comment by acecarruthers** [comment]
I do not know the card number of the tester. My card did not work on my phone, so I will email you my card number and PIN. I tried my account on my iPad and desktop and it was fine. So it appears to just be a phone issue. I tried the EPL-ADULT test authentication account on my phone and it worked fine, too.

**Comment by prestonaustin** [comment]
@jjg do you have logging we could look at to see what these 2 cards do different? If so please coordinate a test with Lisa. I'm baffled as to why some cards would work and others fail on the same phone, with the failing ones then working on iPad and Desktop. Spooky.

**Comment by jjg** [comment]
We can probably use the standard API server logging to sort this out, however I want to make sure I have a crystal-clear understanding of the error.

The same card:

*  Works on iPad and a desktop computer
*  Fails on Phone

Is that correct?  If so, does *any* card work on said phone, or are all attempts to use a card failing on the phone?

Additional helpful details:

*  Desktop O/S version, browser & version
*  Phone make, model O/S version, browser & browser version

Thanks!

**Comment by acecarruthers** [comment]
yes the same card worked on tablet and desktop computer, but did not work on phone. Once the login error message appeared on my phone, the keyboard covered up the library card number box and so I couldn't try any other cards. I did double check that I had put in the correct card number (but I suppose it is still possible that I put it in wrong)

Windows 7, Firefox 39.0 - desktop
Samsung Galaxy S6, Lollipop, Chrome 43.0.2357.93

**Comment by lahollen** [comment]
@jjg check your gmail inbox for @acecarruthers library card and EPL-ADULT test authentication account

**Comment by jjg** [comment]
Got the credentials, I'll take a look now.

**Comment by jjg** [comment]
Bummer, it worked ;)

Here's the log slice from my login attempt.  I don't have an Android phone to test with so I tried it with my phone (iPhone 5s), here's the results (minor details changed for privacy):

`````
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   OPTIONS /auth/users/-REDACTED-
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Authenticating request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   No auth parameter supplied
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Beging processing OPTIONS request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   OPTIONS request complete
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   GET     /auth/users/-REDACTED-
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Authenticating request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   No auth parameter supplied
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Begin processing GET request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   GET request complete
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   OPTIONS /collection
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Authenticating request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   No auth parameter supplied
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       select_method in collection stage
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Beging processing OPTIONS request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   OPTIONS request complete
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   OPTIONS /auth/users
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Authenticating request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   No auth parameter supplied
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Beging processing OPTIONS request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   OPTIONS request complete
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   GET     /collection
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Authenticating request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   POST    /auth/users
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Authenticating request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   No auth parameter supplied
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Begin processing POST request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   POST request body received
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Processing request body for auth endpoint
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Processing new user/user update request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       select_method in collection stage
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   Begin processing GET request
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       Object stored sucessfully to /auth/users/-REDACTED-
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       Object added to index
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   User data stored
Jul 17 20:14:36 musicat-api-1 musicat-api: Fri Jul 17 2015 20:14:36 GMT+0000 (UTC)      1       75.129.147.40   POST request complete
`````

I'm going to check on IM to see if anyone is handy who can test with an Android handset to see if that has a different result, otherwise maybe I can borrow @prestonaustin's old phone next week for debugging?

**Comment by prestonaustin** [comment]
for the record, also just worked fine on my Nexus6 (on fast WiFi) and
Julie's iPhone (on decent Verizon LTE).

**Comment by jjg** [comment]
After some testing we can rule out this being an issue with the SIP gateway authentication mechanism (it doesn't come into play after the user account is created).

Looks like a very tricky (and specific) client issue, I'm going to assign this over to @lahollen for reassignment but let me know if it looks like something internal to the API or if you need access to logs to debug.

**Comment by lahollen** [comment]
@nagapampa see convo above and in hangout - if I'm wrongly assigning you go ahead and assign to the right party

**Comment by nagapampa** [comment]
@acecarruthers I am able to log into your account on my Android Samsung S5 (Verizon).  Can you please retest?

**Comment by acecarruthers** [comment]
@nagapampa I just retested and it worked. Thanks!

**Comment by nagapampa** [comment]
@acecarruthers I'd like to say I fixed it, but I'm not sure what happened.  Maybe it had something to do with the formatting of the modal that I fixed yesterday.  Can this be closed?

**Comment by acecarruthers** [comment]
I think so,yes
