### ISSUE TITLE
Update media pointers to use MMS, ccrapi2

### ISSUE THREAD

**Issue by jjg** [therabble/ccr-app#78]
Now that the media stored on ccrjsfs.murfie.com has been migrated to ccrapi2.murfie.com, update client code and API data to reference the files in the new location, and access them exclusively via MMS.

A detailed log of the migration outcome can be downloaded using the link below (I can provide the access_key to interested parties out-of-band).  This file is JSON data representing the processing status of the migration job and will likely require some processing to comprehend (@mbrakken and I reviewed the a sample from a test run yesterday so he may have a plan for this already)

https://ccrapi2.murfie.com/debug/formatted_processing_state.json

**Comment by mbrakken** [comment]
I'll try to get to this later tonight.

**Comment by mbrakken** [comment]
Pointers for all completed submissions (including the one not yet published) have been updated and tested. There are still 4 submissions yet to be completed by artists, and I haven't touched those. The migrations itself has been show to be successful, so I think we can take care of those remaining ones as necessary. Many artists (~40%?) uploaded new versions of their tracks, replacing the initial submission, so I figure we can wait and see on the last four.

For posterity, this is what I ran for each album:
```javascript
var tr = $E.get('tracks') 
// $E is the var ember objects are set to via the inspector; in this case $E is an album
tr.forEach(function(t){
    if (t.get('url').match(/ccrjsfs.murfie.com/)) {
        var url = t.get('url');
        console.log(url);
        url = url.replace('ccrjsfs.murfie.com', 'ccrapi2.murfie.com/complete-submission/albums');
        url = url.split('.');
        url[url.length - 1] = "wav";
        url = url.join('.');
        t.set('url', url);
        console.log(url);
    }
})
```

**Comment by mbrakken** [comment]
I believe this is done, with the above caveat about the remaining 4 albums. I'm going to close. Reopen if appropriate.
