### ISSUE TITLE
update EPL logo

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#81]
our design team has requested you use the EPL logo at the link below instead of the one that is currently there in the footer. 

https://drive.google.com/open?id=0B56HcVGi1B3nNXJYMU5UQ3dtOGM

**Comment by lahollen** [comment]
@acecarruthers can you give us a PNG version of this logo? Thanks!

**Comment by acecarruthers** [comment]
Sure!
![epl_ca_logo_right_colour](https://cloud.githubusercontent.com/assets/7355887/8808195/55530728-2f9e-11e5-8df7-5de38ef4ccc4.png)

**Comment by nagapampa** [comment]
Will be in next deploy
