### ISSUE TITLE
Switch from MTC to MMS

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#83]
Relevant code is in [services/player.js] (https://github.com/therabble/ccr-app/blob/master/app/services/player.js), the [`playSound()` method] (https://github.com/therabble/ccr-app/blob/master/app/services/player.js#L57).

Currently, I'm not sending mp3, ogg, mp4, or m4a through MTC, due to various issues with playback. We should assess if we also need to keep those formats from hitting MMS (although it's worth noting that Safari doesn't play ogg, if I recall correctly).

Ideally, we just store everything as WAV anyways.

**Comment by jjg** [comment]
All tracks stored on ccrapi2 should now be available in wave format.  Original versions have been preserved at their original locations, and new paths are identical but for a ".wav" extension.

**Comment by lahollen** [comment]
@nagapampa can you pick this up or do you need anything from @mbrakken?

**Comment by mbrakken** [comment]
#87 took care of the switch. There are still 3 tracks not in wav on production, do to some strange artifact. I'll check in with @jjg on Monday about those.

**Comment by prestonaustin** [comment]
@mbrakken Please close this ticket as soon as those three are switched.

**Comment by mbrakken** [comment]
That's my plan @prestonaustin.

**Comment by mbrakken** [comment]
Final 3 tracks are wav and working. Closing.
