### ISSUE TITLE
Text and design edits

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#84]
- [x] in FAQ under "Does this have anything to do with EPL's Makerspace" please link the text "The Makerspace" to www.epl.ca/makerspace (http://wax.capitalcityrecords.ca/faq)
- [x] The login pop up says "Woah there! We'll need you to give us some more information to access that." I really like this message when someone tries to download something and is surprised by the pop up, but as one of our users pointed out, it is confusing for people who intentionally click on "login" (her first thought was that she had hit an error message). Is it possible to change it so that when someone clicks "login" instead of the popup saying "Woah There! We'll need to you....etc. " it just says "Login" without any explanatory text?
- [ ] I need to write a paragraph or two to replace the current introductory text on the About page. I have not written this yet - but I will ASAP!
- [x] A user recommended we write some text to give context to the poster collection. (http://wax.capitalcityrecords.ca/posters) For copyright purposes, it is important that we include a little additional information as well. I've mocked up the edits I think would solve these concerns below. Please use the same font as is otherwise used on the page. The links go to
1) About page
2) FAQ: "How can I contribute concert posters?"
3) About page: "Flagging Content" 

NOTE: "Credit this artist" should go under every poster that has no artist name (and then disappear if I go in and edit the artist name to something else). Is that possible? 

![ccrposters4](https://cloud.githubusercontent.com/assets/7355887/8789175/7914393a-2efd-11e5-93ed-bb2f7c32475b.jpg)

**Comment by nagapampa** [comment]
These are complete and deployed except for the introductory text on the About page.  @acecarruthers Can you create a new ticket for that when it's available?
