### ISSUE TITLE
track playback progress ui

### ISSUE THREAD

**Issue by mbrakken** [therabble/ccr-app#88]
Dependent on #8 and conversion of all tracks to wav. Show playback progress in player.

There's some wip on this in https://github.com/therabble/ccr-app/compare/position, but it may make sense to more or less scrap that branch. The version on the linked branch calculates position off the duration read by the audio element. We could also calculate position off track length saved on track json after #8 is done.

**Comment by jjg** [comment]
All tracks stored on ccrapi2 should now be available in wave format.  Original versions have been preserved at their original locations, and new paths are identical but for a ".wav" extension.

**Comment by nagapampa** [comment]
@mbrakken you said this is dependent on #8 (assigned to you) and all tracks to wav (completed by @jjg)

Did you need me to do something on this?

**Comment by mbrakken** [comment]
I believe #97 addresses this for all but the 45 tracks still in need of updates (@jjg knows of those). That said, once #94 merges we may want to use that static duration data. Otherwise, this is using duration data as the audio element knows of it.
