### ISSUE TITLE
Revise text on about page

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#90]
Replace current text at the top of wax.capitalcityrecords.ca/about (currently "Capital City Records is a digital public space ... and realized by Rabble.") with text on following Google drive page. I added where the links should go in comments. 
@nagapampa this is the remaining issue from #84 

https://drive.google.com/open?id=17umg7G6kQRy2N6qkUT_-ekWzhBjLLcvabQl_vtvTzUo

**Comment by nagapampa** [comment]
Will be in next deploy
