### ISSUE TITLE
Replace banner image for artists

### ISSUE THREAD

**Issue by acecarruthers** [therabble/ccr-app#92]
Please replace the artist banner for Souljah Fyah (https://wax.capitalcityrecords.ca/artists/souljah-fyah) with image 1 below. 

Please replace the artist banner for Mad Bomber Society (https://wax.capitalcityrecords.ca/artists/mad-bomber-society) with image 2 below. 

Image 1:
![sjf2-1](https://cloud.githubusercontent.com/assets/7355887/8885224/d084ac98-321a-11e5-85e0-f0cab1e6a5a7.JPG)

Image 2:
![_mg_5256-5x5-1](https://cloud.githubusercontent.com/assets/7355887/8885311/9dedca16-321b-11e5-916e-3df5509868a8.jpg)

**Comment by prestonaustin** [comment]
@nagapampa Could @acecarruthers do this directly and republish? (If that's blocked I should learn why, and probably create a post production issue to fix/enable that in our meeting Tuesday)

**Comment by acecarruthers** [comment]
The admin interface for publishing artist pages doesn't allow me to replace banner images, unless I'm missing something. 
http://submissions.capitalcityrecords.ca/review-and-publish/submissions

**Comment by mbrakken** [comment]
There currently isn't an interface for @acecarruthers to upload new art, to respect the assumed terms of the license (artists submit content on sign a license for it specifically). 

It'd be pretty easy to add capability to update an image, I think, bearing in mind that it could be used at cross purposes (there's no way to prevent uploading any random image, other than good behavior). However, I'm happy to accept that library folks won't arbitrarily change images and that artists have means of recourse if they do.

If there should be a process to notify artists in the event of librarian-derived updates, that will need to be spec'd.

**Comment by prestonaustin** [comment]
let's just load these for Alex then, I'll follow up on the missing admin
capability elsewhere.
